// TaxPro Universal Multilingual & Localization Engine
import { useState, useEffect } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', country: 'gb', dir: 'ltr' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', country: 'in', dir: 'ltr' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳', country: 'in', dir: 'ltr' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', country: 'ru', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦', country: 'sa', dir: 'rtl' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', country: 'es', dir: 'ltr' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', country: 'fr', dir: 'ltr' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩', country: 'bd', dir: 'ltr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪', country: 'de', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹', country: 'pt', dir: 'ltr' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳', country: 'cn', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', country: 'jp', dir: 'ltr' }
];

export const TRANSLATIONS = {
  "en": {
    "dashboard": "Dashboard",
    "aiStudio": "AI Studio",
    "myWork": "My Work",
    "clients": "Clients",
    "contactPerson": "Contact Person",
    "projects": "Projects",
    "tasks": "Tasks",
    "taskHistory": "Task History",
    "attendance": "Attendance",
    "communication": "Communication",
    "privateChat": "Private Chat",
    "askLeave": "Ask Leave",
    "leaves": "Leaves",
    "teamMembers": "Team Members",
    "departments": "Departments",
    "feesTracking": "Fees Tracking",
    "receiptsPayments": "Receipts & Payments",
    "membersPayment": "Members Payment",
    "membersPaymentStaff": "Members Payment (Staff)",
    "ourPayment": "Our Payment",
    "ourPaymentSalary": "Our Payment (My Salary)",
    "ownerPayments": "Owner Payments",
    "reports": "Reports",
    "activityLogs": "Activity Logs",
    "integrations": "Integrations",
    "calendar": "Calendar",
    "supportHelp": "Support & Help",
    "settings": "Settings",
    "editingTaskbar": "EDITING TASKBAR",
    "doneSaveTaskbar": "Done ✓ Save Taskbar",
    "doneCheck": "Done ✓",
    "done": "Done",
    "doubleTapOrHold": "Double-tap or hold-click any item below to reorder or move it!",
    "moveUp": "Move Up",
    "moveDown": "Move Down",
    "moveToTop": "Move to Top",
    "moveToBottom": "Move to Bottom",
    "resetDefaultOrder": "Reset Default Order",
    "holdClickDragDrop": "Hold-Click Drag & Drop:",
    "position": "Position",
    "slot": "Slot",
    "searchPlaceholder": "Search by Name, Trade Name or File No",
    "search": "Search",
    "lockScreen": "Lock Screen",
    "privacyMode": "Lock Workspace (Privacy Mode)",
    "profile": "Profile",
    "profileCompleted": "Profile Completed",
    "profilePending": "Complete Profile",
    "sync": "Sync",
    "syncing": "Syncing...",
    "complaints": "Complaints",
    "registerComplaint": "Register Complaint",
    "reportComplaint": "Report a Complaint to Management",
    "supportChat": "Support Chat (WhatsApp)",
    "signOut": "Sign Out",
    "setupFirmProfile": "Setup Firm Profile →",
    "returnToDashboard": "Return to Dashboard",
    "accessRestricted": "Access Restricted",
    "addTask": "Add Task",
    "newClient": "New Client",
    "addMember": "Add Member",
    "addDepartment": "Add Department",
    "applyLeave": "Apply Leave",
    "recordPayment": "Record Payment",
    "createInvoice": "Create Invoice",
    "exportPdf": "Export PDF",
    "exportExcel": "Export Excel",
    "exportCsv": "Export CSV",
    "export": "Export",
    "download": "Download",
    "print": "Print",
    "filter": "Filter",
    "edit": "Edit",
    "save": "Save",
    "cancel": "Cancel",
    "delete": "Delete",
    "close": "Close",
    "open": "Open",
    "refresh": "Refresh",
    "reset": "Reset",
    "submit": "Submit",
    "confirm": "Confirm",
    "viewDetails": "View Details",
    "bulkImport": "Bulk Import",
    "all": "All",
    "active": "Active",
    "inactive": "Inactive",
    "pending": "Pending",
    "inProgress": "In Progress",
    "completed": "Completed",
    "paid": "Paid",
    "partiallyPaid": "Partially Paid",
    "unpaid": "Unpaid",
    "overdue": "Overdue",
    "approved": "Approved",
    "rejected": "Rejected",
    "toDo": "To Do",
    "review": "Review",
    "cancelled": "Cancelled",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
    "urgent": "Urgent",
    "normal": "Normal",
    "dueDate": "Due Date",
    "priority": "Priority",
    "status": "Status",
    "action": "Action",
    "actions": "Actions",
    "amount": "Amount",
    "date": "Date",
    "client": "Client",
    "assignee": "Assignee",
    "description": "Description",
    "notes": "Notes",
    "category": "Category",
    "type": "Type",
    "role": "Role",
    "department": "Department",
    "salary": "Salary",
    "checkIn": "Check In",
    "checkOut": "Check Out",
    "title": "Title",
    "summary": "Summary",
    "overview": "Overview",
    "statistics": "Statistics",
    "totalRevenue": "Total Revenue",
    "settledPayments": "Settled Payments",
    "activeClients": "Active Clients",
    "pendingFees": "Pending Fees",
    "totalDeliverables": "Total Deliverables",
    "dailyLiveRegister": "Daily Live Register",
    "monthlyLeavesSalaryCuts": "Monthly Leaves & Salary Cuts",
    "markAllPresent": "Mark All Present",
    "punchIn": "Punch-In",
    "punchOut": "Punch-Out",
    "present": "Present",
    "halfDay": "Half Day",
    "absent": "Absent",
    "onLeave": "On Leave",
    "employeeName": "Employee Name",
    "designatedRole": "Designated Role",
    "workingHours": "Working Hours",
    "currentStatus": "Current Status",
    "employeeDetails": "Employee Details",
    "printDaySheet": "Print Day Sheet",
    "printCutsRegister": "Print Cuts Register",
    "totalStaff": "Total Staff",
    "reportsAnalytics": "Reports & Analytics",
    "financialReports": "Financial Reports",
    "taskReports": "Task Reports",
    "clientReports": "Client Reports",
    "attendanceSummary": "Attendance Summary",
    "gstSummary": "GST Summary",
    "tdsSummary": "TDS Summary",
    "outstandingFees": "Outstanding Fees",
    "generateReport": "Generate Report",
    "viewReport": "View Report",
    "dateRange": "Date Range",
    "fromDate": "From Date",
    "toDate": "To Date",
    "total": "Total",
    "clientMaster": "Client Master",
    "addNewClient": "Add New Client",
    "allClients": "All Clients",
    "taskManagement": "Task Management",
    "createTask": "Create Task",
    "allTasks": "All Tasks",
    "today": "Today",
    "month": "Month",
    "week": "Week",
    "day": "Day",
    "allTransactions": "All Transactions",
    "receipts": "Receipts",
    "payments": "Payments",
    "income": "Income",
    "expense": "Expense",
    "totalInflow": "Total Inflow",
    "totalOutflow": "Total Outflow",
    "netBalance": "Net Balance",
    "addTransaction": "Add Transaction",
    "invoiceNo": "Invoice No",
    "paidAmount": "Paid Amount",
    "pendingAmount": "Pending Amount",
    "paymentMode": "Payment Mode",
    "cash": "Cash",
    "bankTransfer": "Bank Transfer",
    "upi": "UPI",
    "cheque": "Cheque",
    "receipt": "Receipt",
    "printReceipt": "Print Receipt",
    "firmProfile": "Firm Profile",
    "systemPreferences": "System Preferences",
    "userManagement": "User Management",
    "securityPrivacy": "Security & Privacy",
    "backupRestore": "Backup & Restore",
    "languageRegion": "Language & Region",
    "activeSystemLanguage": "Active System Language",
    "theme": "Theme",
    "lightMode": "Light Mode",
    "darkMode": "Dark Mode",
    "zoomLevel": "Zoom Level",
    "saveChanges": "Save Changes",
    "updateProfile": "Update Profile"
  },
  "hi": {
    "dashboard": "डैशबोर्ड",
    "aiStudio": "एआई स्टूडियो",
    "myWork": "मेरा कार्य",
    "clients": "ग्राहक",
    "contactPerson": "संपर्क व्यक्ति",
    "projects": "परियोजनाएं",
    "tasks": "कार्य",
    "taskHistory": "कार्य इतिहास",
    "attendance": "उपस्थिति",
    "communication": "संचार",
    "privateChat": "निजी चैट",
    "askLeave": "छुट्टी का अनुरोध",
    "leaves": "छुट्टियां",
    "teamMembers": "टीम के सदस्य",
    "departments": "विभाग",
    "feesTracking": "फीस ट्रैकिंग",
    "receiptsPayments": "रसीदें और भुगतान",
    "membersPayment": "सदस्यों का भुगतान",
    "membersPaymentStaff": "सदस्यों का भुगतान (कर्मचारी)",
    "ourPayment": "हमारा भुगतान",
    "ourPaymentSalary": "हमारा भुगतान (मेरा वेतन)",
    "ownerPayments": "मालिक का भुगतान",
    "reports": "रिपोर्ट",
    "activityLogs": "गतिविधि लॉग",
    "integrations": "एकीकरण",
    "calendar": "कैलेंडर",
    "supportHelp": "सहायता और समर्थन",
    "settings": "सेटिंग्स",
    "editingTaskbar": "टास्कबार संपादन",
    "doneSaveTaskbar": "पूर्ण ✓ टास्कबार सहेजें",
    "doneCheck": "पूर्ण ✓",
    "done": "पूर्ण",
    "doubleTapOrHold": "पुनः व्यवस्थित करने के लिए नीचे किसी भी आइटम पर डबल-टैप करें या दबाकर रखें!",
    "moveUp": "ऊपर ले जाएं",
    "moveDown": "नीचे ले जाएं",
    "moveToTop": "शीर्ष पर ले जाएं",
    "moveToBottom": "सबसे नीचे ले जाएं",
    "resetDefaultOrder": "डिफ़ॉल्ट क्रम रीसेट करें",
    "holdClickDragDrop": "होल्ड-क्लिक ड्रैग और ड्रॉप:",
    "position": "स्थिति",
    "slot": "स्लॉट",
    "searchPlaceholder": "नाम, व्यापारिक नाम या फ़ाइल संख्या द्वारा खोजें",
    "search": "खोजें",
    "lockScreen": "स्क्रीन लॉक करें",
    "privacyMode": "कार्यक्षेत्र लॉक करें (गोपनीयता मोड)",
    "profile": "प्रोफ़ाइल",
    "profileCompleted": "प्रोफ़ाइल पूर्ण",
    "profilePending": "प्रोफ़ाइल पूरा करें",
    "sync": "सिंक करें",
    "syncing": "सिंक हो रहा है...",
    "complaints": "शिकायतें",
    "registerComplaint": "शिकायत दर्ज करें",
    "reportComplaint": "प्रबंधन को शिकायत दर्ज करें",
    "supportChat": "सहायता चैट (व्हाट्सएप)",
    "signOut": "साइन आउट",
    "setupFirmProfile": "फर्म प्रोफ़ाइल सेटअप करें →",
    "returnToDashboard": "डैशबोर्ड पर लौटें",
    "accessRestricted": "पहुंच प्रतिबंधित है",
    "addTask": "कार्य जोड़ें",
    "newClient": "नया ग्राहक",
    "addMember": "सदस्य जोड़ें",
    "addDepartment": "विभाग जोड़ें",
    "applyLeave": "छुट्टी आवेदन",
    "recordPayment": "भुगतान दर्ज करें",
    "createInvoice": "चालान बनाएं",
    "exportPdf": "पीडीएफ निर्यात",
    "exportExcel": "एक्सेल निर्यात",
    "exportCsv": "सीएसवी निर्यात",
    "export": "निर्यात",
    "download": "डाउनलोड",
    "print": "प्रिंट",
    "filter": "फ़िल्टर",
    "edit": "संपादित करें",
    "save": "सहेजें",
    "cancel": "रद्द करें",
    "delete": "हटाएं",
    "close": "बंद करें",
    "open": "खोलें",
    "refresh": "ताज़ा करें",
    "reset": "रीसेट करें",
    "submit": "जमा करें",
    "confirm": "पुष्टि करें",
    "viewDetails": "विवरण देखें",
    "bulkImport": "थोक आयात",
    "all": "सभी",
    "active": "सक्रिय",
    "inactive": "निष्क्रिय",
    "pending": "लंबित",
    "inProgress": "प्रगति पर है",
    "completed": "पूर्ण",
    "paid": "भुगतान किया गया",
    "partiallyPaid": "आंशिक भुगतान",
    "unpaid": "अदत्त",
    "overdue": "अतिदेय",
    "approved": "स्वीकृत",
    "rejected": "अस्वीकृत",
    "toDo": "करने के लिए",
    "review": "समीक्षा",
    "cancelled": "रद्द किया गया",
    "high": "उच्च",
    "medium": "मध्यम",
    "low": "कम",
    "urgent": "तत्काल",
    "normal": "सामान्य",
    "dueDate": "नियत तारीख",
    "priority": "प्राथमिकता",
    "status": "स्थिति",
    "action": "कार्रवाई",
    "actions": "कार्रवाइयां",
    "amount": "राशि",
    "date": "तारीख",
    "client": "ग्राहक",
    "assignee": "सौंपा गया व्यक्ति",
    "description": "विवरण",
    "notes": "टिप्पणियां",
    "category": "श्रेणी",
    "type": "प्रकार",
    "role": "भूमिका",
    "department": "विभाग",
    "salary": "वेतन",
    "checkIn": "चेक इन",
    "checkOut": "चेक आउट",
    "title": "शीर्षक",
    "summary": "सारांश",
    "overview": "अवलोकन",
    "statistics": "आंकड़े",
    "totalRevenue": "कुल राजस्व",
    "settledPayments": "निपटारा भुगतान",
    "activeClients": "सक्रिय ग्राहक",
    "pendingFees": "लंबित शुल्क",
    "totalDeliverables": "कुल कार्य परिणाम",
    "dailyLiveRegister": "दैनिक लाइव रजिस्टर",
    "monthlyLeavesSalaryCuts": "मासिक अवकाश और वेतन कटौती",
    "markAllPresent": "सभी को उपस्थित चिह्नित करें",
    "punchIn": "पंच-इन",
    "punchOut": "पंच-आउट",
    "present": "उपस्थित",
    "halfDay": "आधा दिन",
    "absent": "अनुपस्थित",
    "onLeave": "छुट्टी पर",
    "employeeName": "कर्मचारी का नाम",
    "designatedRole": "निर्दिष्ट पद",
    "workingHours": "काम के घंटे",
    "currentStatus": "वर्तमान स्थिति",
    "employeeDetails": "कर्मचारी का विवरण",
    "printDaySheet": "दिन की शीट प्रिंट करें",
    "printCutsRegister": "कटौती रजिस्टर प्रिंट करें",
    "totalStaff": "कुल कर्मचारी",
    "reportsAnalytics": "रिपोर्ट और विश्लेषण",
    "financialReports": "वित्तीय रिपोर्ट",
    "taskReports": "कार्य रिपोर्ट",
    "clientReports": "ग्राहक रिपोर्ट",
    "attendanceSummary": "उपस्थिति सारांश",
    "gstSummary": "जीएसटी सारांश",
    "tdsSummary": "टीडीएस सारांश",
    "outstandingFees": "बकाया शुल्क",
    "generateReport": "रिपोर्ट तैयार करें",
    "viewReport": "रिपोर्ट देखें",
    "dateRange": "तारीख सीमा",
    "fromDate": "आरंभिक तारीख",
    "toDate": "अंतिम तारीख",
    "total": "कुल",
    "clientMaster": "ग्राहक मास्टर",
    "addNewClient": "नया ग्राहक जोड़ें",
    "allClients": "सभी ग्राहक",
    "taskManagement": "कार्य प्रबंधन",
    "createTask": "कार्य बनाएं",
    "allTasks": "सभी कार्य",
    "today": "आज",
    "month": "महीना",
    "week": "सप्ताह",
    "day": "दिन",
    "allTransactions": "सभी लेन-देन",
    "receipts": "रसीदें",
    "payments": "भुगतान",
    "income": "आय",
    "expense": "व्यय",
    "totalInflow": "कुल आवक",
    "totalOutflow": "कुल जावक",
    "netBalance": "शुद्ध शेष",
    "addTransaction": "लेन-देन जोड़ें",
    "invoiceNo": "चालान संख्या",
    "paidAmount": "भुगतान की गई राशि",
    "pendingAmount": "लंबित राशि",
    "paymentMode": "भुगतान का तरीका",
    "cash": "नकद",
    "bankTransfer": "बैंक ट्रांसफर",
    "upi": "यूपीआई",
    "cheque": "चेक",
    "receipt": "रसीद",
    "printReceipt": "रसीद प्रिंट करें",
    "firmProfile": "फर्म प्रोफ़ाइल",
    "systemPreferences": "सिस्टम प्राथमिकताएं",
    "userManagement": "उपयोगकर्ता प्रबंधन",
    "securityPrivacy": "सुरक्षा और गोपनीयता",
    "backupRestore": "बैकअप और पुनर्स्थापना",
    "languageRegion": "भाषा और क्षेत्र",
    "activeSystemLanguage": "सक्रिय सिस्टम भाषा",
    "theme": "थीम",
    "lightMode": "लाइट मोड",
    "darkMode": "डार्क मोड",
    "zoomLevel": "ज़ूम स्तर",
    "saveChanges": "परिवर्तन सहेजें",
    "updateProfile": "प्रोफ़ाइल अपडेट करें"
  },
  "gu": {
    "dashboard": "ડેશબોર્ડ",
    "aiStudio": "એઆઈ સ્ટુડિયો",
    "myWork": "મારું કાર્ય",
    "clients": "ક્લાયન્ટ્સ",
    "contactPerson": "સંપર્ક વ્યક્તિ",
    "projects": "પ્રોજેક્ટ્સ",
    "tasks": "કાર્યો",
    "taskHistory": "કાર્ય ઇતિહાસ",
    "attendance": "હાજરી",
    "communication": "સંદેશાવ્યવહાર",
    "privateChat": "ખાનગી ચેટ",
    "askLeave": "રજા માટે અરજી",
    "leaves": "રજાઓ",
    "teamMembers": "ટીમ સભ્યો",
    "departments": "વિભાગો",
    "feesTracking": "ફી ટ્રેકિંગ",
    "receiptsPayments": "પાવતી અને ચુકવણી",
    "membersPayment": "સભ્યોની ચુકવણી",
    "membersPaymentStaff": "સભ્યોની ચુકવણી (સ્ટાફ)",
    "ourPayment": "અમારી ચુકવણી",
    "ourPaymentSalary": "અમારી ચુકવણી (મારો પગાર)",
    "ownerPayments": "માલિકની ચુકવણી",
    "reports": "રિપોર્ટ્સ",
    "activityLogs": "પ્રવૃત્તિ લૉગ્સ",
    "integrations": "ઇન્ટિગ્રેશન્સ",
    "calendar": "કેલેન્ડર",
    "supportHelp": "સહાય અને સપોર્ટ",
    "settings": "સેટિંગ્સ",
    "editingTaskbar": "ટાસ્કબાર સંપાદન",
    "doneSaveTaskbar": "પૂર્ણ ✓ ટાસ્કબાર સાચવો",
    "doneCheck": "પૂર્ણ ✓",
    "done": "સંપન્ન",
    "doubleTapOrHold": "ક્રમ બદલવા માટે નીચેની કોઈપણ વસ્તુ પર ડબલ-ટેપ કરો અથવા પકડી રાખો!",
    "moveUp": "ઉપર ખસેડો",
    "moveDown": "નીચે ખસેડો",
    "moveToTop": "સૌથી ઉપર લઈ જાઓ",
    "moveToBottom": "સૌથી નીચે લઈ જાઓ",
    "resetDefaultOrder": "ડિફૉલ્ટ ક્રમ ફરી સેટ કરો",
    "holdClickDragDrop": "હોલ્ડ-ક્લિક ડ્રેગ અને ડ્રોપ:",
    "position": "સ્થિતિ",
    "slot": "સ્લોટ",
    "searchPlaceholder": "નામ, ટ્રેડ નામ અથવા ફાઇલ નંબર દ્વારા શોધો",
    "search": "શોધો",
    "lockScreen": "સ્ક્રીન લૉક કરો",
    "privacyMode": "વર્કસ્પેસ લૉક કરો (ગોપનીયતા મોડ)",
    "profile": "પ્રોફાઇલ",
    "profileCompleted": "પ્રોફાઇલ પૂર્ણ",
    "profilePending": "પ્રોફાઇલ પૂર્ણ કરો",
    "sync": "સમન્વયિત કરો",
    "syncing": "સમન્વય થઈ રહ્યું છે...",
    "complaints": "ફરિયાદો",
    "registerComplaint": "ફરિયાદ નોંધાવો",
    "reportComplaint": "સંચાલનને ફરિયાદ નોંધાવો",
    "supportChat": "સપોર્ટ ચેટ (વ્હોટ્સએપ)",
    "signOut": "સાઇન આઉટ",
    "setupFirmProfile": "ફર્મ પ્રોફાઇલ સેટ કરો →",
    "returnToDashboard": "ડેશબોર્ડ પર પાછા ફરો",
    "accessRestricted": "પ્રવેશ પ્રતિબંધિત છે",
    "addTask": "કાર્ય ઉમેરો",
    "newClient": "નવો ક્લાયન્ટ",
    "addMember": "સભ્ય ઉમેરો",
    "addDepartment": "વિભાગ ઉમેરો",
    "applyLeave": "રજા માટે અરજી કરો",
    "recordPayment": "ચુકવણી નોંધાવો",
    "createInvoice": "ઇનવોઇસ બનાવો",
    "exportPdf": "પીડીએફ નિકાસ",
    "exportExcel": "એક્સેલ નિકાસ",
    "exportCsv": "સીએસવી નિકાસ",
    "export": "નિકાસ",
    "download": "ડાઉનલોડ",
    "print": "પ્રિન્ટ",
    "filter": "ફિલ્ટર",
    "edit": "સંપાદિત કરો",
    "save": "સાચવો",
    "cancel": "રદ કરો",
    "delete": "કાઢી નાખો",
    "close": "બંધ કરો",
    "open": "ખોલો",
    "refresh": "રિફ્રેશ કરો",
    "reset": "રીસેટ કરો",
    "submit": "સબમિટ કરો",
    "confirm": "ખાતરી કરો",
    "viewDetails": "વિગતો જુઓ",
    "bulkImport": "બલ્ક આયાત",
    "all": "બધા",
    "active": "સક્રિય",
    "inactive": "નિષ્ક્રિય",
    "pending": "બાકી",
    "inProgress": "ચાલુ છે",
    "completed": "પૂર્ણ થયેલ",
    "paid": "ચુકવેલ",
    "partiallyPaid": "આંશિક ચુકવેલ",
    "unpaid": "ન ચૂકવાયેલ",
    "overdue": "મુદતવીતી ગયેલ",
    "approved": "મંજૂર થયેલ",
    "rejected": "અસ્વીકાર્ય",
    "toDo": "કરવા માટે",
    "review": "સમીક્ષા",
    "cancelled": "રદ કરેલ",
    "high": "ઉચ્ચ",
    "medium": "મધ્યમ",
    "low": "ઓછું",
    "urgent": "તાકીદનું",
    "normal": "સામાન્ય",
    "dueDate": "નિયત તારીખ",
    "priority": "પ્રાધાન્યતા",
    "status": "સ્થિતિ",
    "action": "ક્રિયા",
    "actions": "ક્રિયાઓ",
    "amount": "રકમ",
    "date": "તારીખ",
    "client": "ક્લાયન્ટ",
    "assignee": "સોંપાયેલ વ્યક્તિ",
    "description": "વર્ણન",
    "notes": "નોંધો",
    "category": "શ્રેણી",
    "type": "પ્રકાર",
    "role": "ભૂમિકા",
    "department": "વિભાગ",
    "salary": "પગાર",
    "checkIn": "ચેક ઇન",
    "checkOut": "ચેક આઉટ",
    "title": "શીર્ષક",
    "summary": "સારાંશ",
    "overview": "વિહંગાવલોકન",
    "statistics": "આંકડા",
    "totalRevenue": "કુલ આવક",
    "settledPayments": "ચુકવાયેલ પેમેન્ટ",
    "activeClients": "સક્રિય ક્લાયન્ટ્સ",
    "pendingFees": "બાકી ફી",
    "totalDeliverables": "કુલ ડિલિવરેબલ્સ",
    "dailyLiveRegister": "દૈનિક લાઇવ રજિસ્ટર",
    "monthlyLeavesSalaryCuts": "માસિક રજાઓ અને પગાર કાપ",
    "markAllPresent": "બધાને હાજર માર્ક કરો",
    "punchIn": "પંચ-ઇન",
    "punchOut": "પંચ-આઉટ",
    "present": "હાજર",
    "halfDay": "અડધો દિવસ",
    "absent": "ગેરહાજર",
    "onLeave": "રજા પર",
    "employeeName": "કર્મચારીનું નામ",
    "designatedRole": "નિયુક્ત પદ",
    "workingHours": "કામના કલાકો",
    "currentStatus": "વર્તમાન સ્થિતિ",
    "employeeDetails": "કર્મચારીની વિગતો",
    "printDaySheet": "દિવસની શીટ પ્રિન્ટ કરો",
    "printCutsRegister": "કપાત રજિસ્ટર પ્રિન્ટ કરો",
    "totalStaff": "કુલ સ્ટાફ",
    "reportsAnalytics": "રિપોર્ટ્સ અને એનાલિટિક્સ",
    "financialReports": "નાણાકીય અહેવાલો",
    "taskReports": "કાર્ય અહેવાલો",
    "clientReports": "ક્લાયન્ટ અહેવાલો",
    "attendanceSummary": "હાજરી સારાંશ",
    "gstSummary": "જીએસટી સારાંશ",
    "tdsSummary": "ટીડીએસ સારાંશ",
    "outstandingFees": "બાકી ફી",
    "generateReport": "અહેવાલ બનાવો",
    "viewReport": "અહેવાલ જુઓ",
    "dateRange": "તારીખ શ્રેણી",
    "fromDate": "પ્રારંભ તારીખ",
    "toDate": "અંતિમ તારીખ",
    "total": "કુલ",
    "clientMaster": "ક્લાયન્ટ માસ્ટર",
    "addNewClient": "નવો ક્લાયન્ટ ઉમેરો",
    "allClients": "બધા ક્લાયન્ટ્સ",
    "taskManagement": "કાર્ય સંચાલન",
    "createTask": "કાર્ય બનાવો",
    "allTasks": "બધા કાર્યો",
    "today": "આજે",
    "month": "મહિનો",
    "week": "અઠવાડિયું",
    "day": "દિવસ",
    "allTransactions": "બધા વ્યવહારો",
    "receipts": "પાવતીઓ",
    "payments": "ચુકવણીઓ",
    "income": "આવક",
    "expense": "ખર્ચ",
    "totalInflow": "કુલ આવક",
    "totalOutflow": "કુલ જાવક",
    "netBalance": "ચોખ્ખી સિલક",
    "addTransaction": "વ્યવહાર ઉમેરો",
    "invoiceNo": "ઇનવોઇસ નંબર",
    "paidAmount": "ચુકવેલ રકમ",
    "pendingAmount": "બાકી રકમ",
    "paymentMode": "ચુકવણી પદ્ધતિ",
    "cash": "રોકડ",
    "bankTransfer": "બેંક ટ્રાન્સફર",
    "upi": "યુપીઆઈ",
    "cheque": "ચેક",
    "receipt": "પાવતી",
    "printReceipt": "પાવતી પ્રિન્ટ કરો",
    "firmProfile": "ફર્મ પ્રોફાઇલ",
    "systemPreferences": "સિસ્ટમ પસંદગીઓ",
    "userManagement": "વપરાશકર્તા સંચાલન",
    "securityPrivacy": "સુરક્ષા અને ગોપનીયતા",
    "backupRestore": "બેકઅપ અને પુનઃસ્થાપન",
    "languageRegion": "ભાષા અને પ્રદેશ",
    "activeSystemLanguage": "સક્રિય સિસ્ટમ ભાષા",
    "theme": "થીમ",
    "lightMode": "લાઇટ મોડ",
    "darkMode": "ડાર્ક મોડ",
    "zoomLevel": "ઝૂમ સ્તર",
    "saveChanges": "ફેરફારો સાચવો",
    "updateProfile": "પ્રોફાઇલ અપડેટ કરો"
  },
  "ru": {
    "dashboard": "Панель управления",
    "aiStudio": "AI Студия",
    "myWork": "Моя работа",
    "clients": "Клиенты",
    "contactPerson": "Контактное лицо",
    "projects": "Проекты",
    "tasks": "Задачи",
    "taskHistory": "История задач",
    "attendance": "Посещаемость",
    "communication": "Связь",
    "privateChat": "Приватный чат",
    "askLeave": "Запросить отпуск",
    "leaves": "Отпуска",
    "teamMembers": "Члены команды",
    "departments": "Отделы",
    "feesTracking": "Отслеживание сборов",
    "receiptsPayments": "Квитанции и платежи",
    "membersPayment": "Выплаты участникам",
    "membersPaymentStaff": "Выплаты персоналу",
    "ourPayment": "Наш платеж",
    "ourPaymentSalary": "Наш платеж (Моя зарплата)",
    "ownerPayments": "Выплаты владельцу",
    "reports": "Отчеты",
    "activityLogs": "Журнал активности",
    "integrations": "Интеграции",
    "calendar": "Календарь",
    "supportHelp": "Поддержка и помощь",
    "settings": "Настройки",
    "editingTaskbar": "РЕДАКТИРОВАНИЕ ПАНЕЛИ",
    "doneSaveTaskbar": "Готово ✓ Сохранить панель",
    "doneCheck": "Готово ✓",
    "done": "Готово",
    "doubleTapOrHold": "Дважды нажмите или удерживайте любой элемент для перемещения!",
    "moveUp": "Вверх",
    "moveDown": "Вниз",
    "moveToTop": "В самый верх",
    "moveToBottom": "В самый низ",
    "resetDefaultOrder": "Сбросить порядок",
    "holdClickDragDrop": "Удерживайте и перетаскивайте:",
    "position": "Позиция",
    "slot": "Слот",
    "searchPlaceholder": "Поиск по имени, названию или номеру дела",
    "search": "Поиск",
    "lockScreen": "Заблокировать экран",
    "privacyMode": "Блокировка (Приватный режим)",
    "profile": "Профиль",
    "profileCompleted": "Профиль заполнен",
    "profilePending": "Заполните профиль",
    "sync": "Синхронизация",
    "syncing": "Синхронизация...",
    "complaints": "Жалобы",
    "registerComplaint": "Подать жалобу",
    "reportComplaint": "Сообщить руководству о жалобе",
    "supportChat": "Чат поддержки (WhatsApp)",
    "signOut": "Выйти",
    "setupFirmProfile": "Настроить профиль фирмы →",
    "returnToDashboard": "Вернуться на главную",
    "accessRestricted": "Доступ ограничен",
    "addTask": "Добавить задачу",
    "newClient": "Новый клиент",
    "addMember": "Добавить участника",
    "addDepartment": "Добавить отдеल",
    "applyLeave": "Подать заявление на отпуск",
    "recordPayment": "Записать платеж",
    "createInvoice": "Создать счет",
    "exportPdf": "Экспорт PDF",
    "exportExcel": "Экспорт Excel",
    "exportCsv": "Экспорт CSV",
    "export": "Экспорт",
    "download": "Скачать",
    "print": "Печать",
    "filter": "Фильтр",
    "edit": "Изменить",
    "save": "Сохранить",
    "cancel": "Отмена",
    "delete": "Удалить",
    "close": "Закрыть",
    "open": "Открыть",
    "refresh": "Обновить",
    "reset": "Сброс",
    "submit": "Отправить",
    "confirm": "Подтвердить",
    "viewDetails": "Подробнее",
    "bulkImport": "Массовый импорт",
    "all": "Все",
    "active": "Активный",
    "inactive": "Неактивный",
    "pending": "В ожидании",
    "inProgress": "В процессе",
    "completed": "Завершено",
    "paid": "Оплачено",
    "partiallyPaid": "Частично оплачено",
    "unpaid": "Не оплачено",
    "overdue": "Просрочено",
    "approved": "Одобрено",
    "rejected": "Отклонено",
    "toDo": "Сделать",
    "review": "Проверка",
    "cancelled": "Отменено",
    "high": "Высокий",
    "medium": "Средний",
    "low": "Низкий",
    "urgent": "Срочно",
    "normal": "Обычный",
    "dueDate": "Срок выполнения",
    "priority": "Приоритет",
    "status": "Статус",
    "action": "Действие",
    "actions": "Действия",
    "amount": "Сумма",
    "date": "Дата",
    "client": "Клиент",
    "assignee": "Исполнитель",
    "description": "Описание",
    "notes": "Заметки",
    "category": "Категория",
    "type": "Тип",
    "role": "Роль",
    "department": "Отдел",
    "salary": "Зарплата",
    "checkIn": "Вход",
    "checkOut": "Выход",
    "title": "Заголовок",
    "summary": "Сводка",
    "overview": "Обзор",
    "statistics": "Статистика",
    "totalRevenue": "Общая выручка",
    "settledPayments": "Урегулированные платежи",
    "activeClients": "Активные клиенты",
    "pendingFees": "Ожидающие сборы",
    "totalDeliverables": "Всего результатов",
    "dailyLiveRegister": "Ежедневный журнал",
    "monthlyLeavesSalaryCuts": "Ежемесячные отпуска и вычеты",
    "markAllPresent": "Отметить всех присутствующими",
    "punchIn": "Отметка входа",
    "punchOut": "Отметка выхода",
    "present": "Присутствует",
    "halfDay": "Полдня",
    "absent": "Отсутствует",
    "onLeave": "В отпуске",
    "employeeName": "Имя сотрудника",
    "designatedRole": "Назначенная должность",
    "workingHours": "Рабочие часы",
    "currentStatus": "Текущий статус",
    "employeeDetails": "Данные сотрудника",
    "printDaySheet": "Печать дневного листа",
    "printCutsRegister": "Печать вычетов",
    "totalStaff": "Всего персонала",
    "reportsAnalytics": "Отчеты и аналитика",
    "financialReports": "Финансовые отчеты",
    "taskReports": "Отчеты по задачам",
    "clientReports": "Отчеты по клиентам",
    "attendanceSummary": "Сводка посещаемости",
    "gstSummary": "Сводка по GST",
    "tdsSummary": "Сводка по TDS",
    "outstandingFees": "Непогашенные сборы",
    "generateReport": "Создать отчет",
    "viewReport": "Просмотр отчета",
    "dateRange": "Диапазон дат",
    "fromDate": "С даты",
    "toDate": "По дату",
    "total": "Всего",
    "clientMaster": "База клиентов",
    "addNewClient": "Добавить клиента",
    "allClients": "Все клиенты",
    "taskManagement": "Управление задачами",
    "createTask": "Создать задачу",
    "allTasks": "Все задачи",
    "today": "Сегодня",
    "month": "Месяц",
    "week": "Неделя",
    "day": "День",
    "allTransactions": "Все транзакции",
    "receipts": "Квитанции",
    "payments": "Платежи",
    "income": "Доход",
    "expense": "Расход",
    "totalInflow": "Общий приток",
    "totalOutflow": "Общий отток",
    "netBalance": "Чистый баланс",
    "addTransaction": "Добавить транзакцию",
    "invoiceNo": "Номер счета",
    "paidAmount": "Оплаченная сумма",
    "pendingAmount": "Остаток к оплате",
    "paymentMode": "Способ оплаты",
    "cash": "Наличные",
    "bankTransfer": "Банковский перевод",
    "upi": "UPI",
    "cheque": "Чек",
    "receipt": "Квитанция",
    "printReceipt": "Печать квитанции",
    "firmProfile": "Профиль фирмы",
    "systemPreferences": "Системные настройки",
    "userManagement": "Управление пользователями",
    "securityPrivacy": "Безопасность и конфиденциальность",
    "backupRestore": "Резервное копирование",
    "languageRegion": "Язык и регион",
    "activeSystemLanguage": "Текущий язык системы",
    "theme": "Тема оформления",
    "lightMode": "Светлая тема",
    "darkMode": "Темная тема",
    "zoomLevel": "Масштаб",
    "saveChanges": "Сохранить изменения",
    "updateProfile": "Обновить профиль"
  },
  "ar": {
    "dashboard": "لوحة التحكم",
    "aiStudio": "استوديو الذكاء الاصطناعي",
    "myWork": "عملي",
    "clients": "العملاء",
    "contactPerson": "الشخص المسؤول",
    "projects": "المشاريع",
    "tasks": "المهام",
    "taskHistory": "سجل المهام",
    "attendance": "الحضور",
    "communication": "التواصل",
    "privateChat": "دردشة خاصة",
    "askLeave": "طلب إجازة",
    "leaves": "الإجازات",
    "teamMembers": "أعضاء الفريق",
    "departments": "الأقسام",
    "feesTracking": "تتبع الرسوم",
    "receiptsPayments": "المقبوضات والمدفوعات",
    "membersPayment": "مدفوعات الأعضاء",
    "membersPaymentStaff": "مدفوعات الموظفين",
    "ourPayment": "مدفوعاتنا",
    "ourPaymentSalary": "مدفوعاتنا (راتبي)",
    "ownerPayments": "مدفوعات المالك",
    "reports": "التقارير",
    "activityLogs": "سجلات النشاط",
    "integrations": "التكاملات",
    "calendar": "التقويم",
    "supportHelp": "الدعم والمساعدة",
    "settings": "الإعدادات",
    "editingTaskbar": "تعديل شريط المهام",
    "doneSaveTaskbar": "تم ✓ حفظ شريط المهام",
    "doneCheck": "تم ✓",
    "done": "تم",
    "doubleTapOrHold": "انقر نقرًا مزدوجًا أو اضغط مطولاً على أي عنصر لإعادة ترتيبه!",
    "moveUp": "تحريك لأعلى",
    "moveDown": "تحريك لأسفل",
    "moveToTop": "إلى الأعلى تماماً",
    "moveToBottom": "إلى الأسفل تماماً",
    "resetDefaultOrder": "استعادة الترتيب الافتراضي",
    "holdClickDragDrop": "الضغط والسحب والإفلات:",
    "position": "الموقع",
    "slot": "خانة",
    "searchPlaceholder": "البحث بالاسم أو الاسم التجاري أو رقم الملف",
    "search": "بحث",
    "lockScreen": "قفل الشاشة",
    "privacyMode": "قفل مساحة العمل (وضع الخصوصية)",
    "profile": "الملف الشخصي",
    "profileCompleted": "الملف مكتمل",
    "profilePending": "أكمل الملف",
    "sync": "مزامنة",
    "syncing": "جارٍ المزامنة...",
    "complaints": "الشكاوى",
    "registerComplaint": "تسجيل شكوى",
    "reportComplaint": "إبلاغ الإدارة عن شكوى",
    "supportChat": "محادثة الدعم (واتساب)",
    "signOut": "تسجيل الخروج",
    "setupFirmProfile": "إعداد ملف الشركة →",
    "returnToDashboard": "العودة إلى لوحة التحكم",
    "accessRestricted": "الدخول مقيد",
    "addTask": "إضافة مهمة",
    "newClient": "عميل جديد",
    "addMember": "إضافة عضو",
    "addDepartment": "إضافة قسم",
    "applyLeave": "تقديم طلب إجازة",
    "recordPayment": "تسجيل دفعة",
    "createInvoice": "إنشاء فاتورة",
    "exportPdf": "تصدير PDF",
    "exportExcel": "تصدير إكسل",
    "exportCsv": "تصدير CSV",
    "export": "تصدير",
    "download": "تحميل",
    "print": "طباعة",
    "filter": "تصفية",
    "edit": "تعديل",
    "save": "حفظ",
    "cancel": "إلغاء",
    "delete": "حذف",
    "close": "إغلاق",
    "open": "فتح",
    "refresh": "تحديث",
    "reset": "إعادة تعيين",
    "submit": "إرسال",
    "confirm": "تأكيد",
    "viewDetails": "عرض التفاصيل",
    "bulkImport": "استيراد جماعي",
    "all": "الكل",
    "active": "نشط",
    "inactive": "غير نشط",
    "pending": "معلق",
    "inProgress": "قيد التنفيذ",
    "completed": "مكتمل",
    "paid": "مدفوع",
    "partiallyPaid": "مدفوع جزئياً",
    "unpaid": "غير مدفوع",
    "overdue": "متأخر",
    "approved": "معتمد",
    "rejected": "مرفوض",
    "toDo": "قيد الانتظار",
    "review": "مراجعة",
    "cancelled": "ملغى",
    "high": "عالي",
    "medium": "متوسط",
    "low": "منخفض",
    "urgent": "عاجل",
    "normal": "عادي",
    "dueDate": "تاريخ الاستحقاق",
    "priority": "الأولوية",
    "status": "الحالة",
    "action": "إجراء",
    "actions": "الإجراءات",
    "amount": "المبلغ",
    "date": "التاريخ",
    "client": "العميل",
    "assignee": "المكلف",
    "description": "الوصف",
    "notes": "ملاحظات",
    "category": "الفئة",
    "type": "النوع",
    "role": "الدور",
    "department": "القسم",
    "salary": "الراتب",
    "checkIn": "تسجيل الدخول",
    "checkOut": "تسجيل الخروج",
    "title": "العنوان",
    "summary": "الملخص",
    "overview": "نظرة عامة",
    "statistics": "الإحصائيات",
    "totalRevenue": "إجمالي الإيرادات",
    "settledPayments": "المدفوعات المسواة",
    "activeClients": "العملاء النشطون",
    "pendingFees": "الرسوم المعلقة",
    "totalDeliverables": "إجمالي التسليمات",
    "dailyLiveRegister": "السجل اليومي المباشر",
    "monthlyLeavesSalaryCuts": "الإجازات الشهرية والخصومات",
    "markAllPresent": "تحديد الكل حاضر",
    "punchIn": "تسجيل الحضور",
    "punchOut": "تسجيل الانصراف",
    "present": "حاضر",
    "halfDay": "نصف يوم",
    "absent": "غائب",
    "onLeave": "في إجازة",
    "employeeName": "اسم الموظف",
    "designatedRole": "الدور المحدد",
    "workingHours": "ساعات العمل",
    "currentStatus": "الحالة الحالية",
    "employeeDetails": "تفاصيل الموظف",
    "printDaySheet": "طباعة كشف اليوم",
    "printCutsRegister": "طباعة سجل الخصومات",
    "totalStaff": "إجمالي الموظفين",
    "reportsAnalytics": "التقارير والتحليلات",
    "financialReports": "التقارير المالية",
    "taskReports": "تقارير المهام",
    "clientReports": "تقارير العملاء",
    "attendanceSummary": "ملخص الحضور",
    "gstSummary": "ملخص ضريبة السلع والخدمات",
    "tdsSummary": "ملخص اقتطاع الضريبة",
    "outstandingFees": "الرسوم المستحقة",
    "generateReport": "إنشاء تقرير",
    "viewReport": "عرض التقرير",
    "dateRange": "النطاق الزمني",
    "fromDate": "من تاريخ",
    "toDate": "إلى تاريخ",
    "total": "المجموع",
    "clientMaster": "سجل العملاء الرئيسي",
    "addNewClient": "إضافة عميل جديد",
    "allClients": "جميع العملاء",
    "taskManagement": "إدارة المهام",
    "createTask": "إنشاء مهمة",
    "allTasks": "جميع المهام",
    "today": "اليوم",
    "month": "شهر",
    "week": "أسبوع",
    "day": "يوم",
    "allTransactions": "جميع المعاملات",
    "receipts": "الإيصالات",
    "payments": "المدفوعات",
    "income": "الدخل",
    "expense": "المصروفات",
    "totalInflow": "إجمالي التدفق الداخلي",
    "totalOutflow": "إجمالي التدفق الخارجي",
    "netBalance": "الرصيد الصافي",
    "addTransaction": "إضافة معاملة",
    "invoiceNo": "رقم الفاتورة",
    "paidAmount": "المبلغ المدفوع",
    "pendingAmount": "المبلغ المعلق",
    "paymentMode": "طريقة الدفع",
    "cash": "نقداً",
    "bankTransfer": "تحويل بنكي",
    "upi": "UPI",
    "cheque": "شيك",
    "receipt": "إيصال",
    "printReceipt": "طباعة الإيصال",
    "firmProfile": "ملف الشركة",
    "systemPreferences": "تفضيلات النظام",
    "userManagement": "إدارة المستخدمين",
    "securityPrivacy": "الأمان والخصوصية",
    "backupRestore": "النسخ الاحتياطي والاستعادة",
    "languageRegion": "اللغة والمنطقة",
    "activeSystemLanguage": "لغة النظام النشطة",
    "theme": "المظهر",
    "lightMode": "الوضع الفاتح",
    "darkMode": "الوضع الداكن",
    "zoomLevel": "مستوى التكبير",
    "saveChanges": "حفظ التغييرات",
    "updateProfile": "تحديث الملف الشخصي"
  },
  "es": {
    "dashboard": "Panel de control",
    "aiStudio": "Estudio de IA",
    "myWork": "Mi trabajo",
    "clients": "Clientes",
    "contactPerson": "Persona de contacto",
    "projects": "Proyectos",
    "tasks": "Tareas",
    "taskHistory": "Historial de tareas",
    "attendance": "Asistencia",
    "communication": "Comunicación",
    "privateChat": "Chat privado",
    "askLeave": "Pedir permiso",
    "leaves": "Permisos",
    "teamMembers": "Miembros del equipo",
    "departments": "Departamentos",
    "feesTracking": "Seguimiento de honorarios",
    "receiptsPayments": "Recibos y pagos",
    "membersPayment": "Pago a miembros",
    "membersPaymentStaff": "Pago a miembros (Personal)",
    "ourPayment": "Nuestro pago",
    "ourPaymentSalary": "Nuestro pago (Mi salario)",
    "ownerPayments": "Pagos del propietario",
    "reports": "Informes",
    "activityLogs": "Registros de actividad",
    "integrations": "Integraciones",
    "calendar": "Calendario",
    "supportHelp": "Soporte y ayuda",
    "settings": "Configuración",
    "editingTaskbar": "EDITANDO BARRA",
    "doneSaveTaskbar": "Listo ✓ Guardar barra",
    "doneCheck": "Listo ✓",
    "done": "Listo",
    "doubleTapOrHold": "¡Toca dos veces o mantén presionado cualquier elemento para reordenar!",
    "moveUp": "Mover arriba",
    "moveDown": "Mover abajo",
    "moveToTop": "Mover al inicio",
    "moveToBottom": "Mover al final",
    "resetDefaultOrder": "Restablecer orden",
    "holdClickDragDrop": "Mantén presionado y arrastra:",
    "position": "Posición",
    "slot": "Ranura",
    "searchPlaceholder": "Buscar por nombre, razón social o expediente",
    "search": "Buscar",
    "lockScreen": "Bloquear pantalla",
    "privacyMode": "Bloquear área (Modo Privacidad)",
    "profile": "Perfil",
    "profileCompleted": "Perfil completado",
    "profilePending": "Completar perfil",
    "sync": "Sincronizar",
    "syncing": "Sincronizando...",
    "complaints": "Quejas",
    "registerComplaint": "Registrar queja",
    "reportComplaint": "Reportar queja a la gerencia",
    "supportChat": "Chat de soporte (WhatsApp)",
    "signOut": "Cerrar sesión",
    "setupFirmProfile": "Configurar perfil de la firma →",
    "returnToDashboard": "Volver al panel",
    "accessRestricted": "Acceso restringido",
    "addTask": "Agregar tarea",
    "newClient": "Nuevo cliente",
    "addMember": "Agregar miembro",
    "addDepartment": "Agregar departamento",
    "applyLeave": "Solicitar permiso",
    "recordPayment": "Registrar pago",
    "createInvoice": "Crear factura",
    "exportPdf": "Exportar PDF",
    "exportExcel": "Exportar Excel",
    "exportCsv": "Exportar CSV",
    "export": "Exportar",
    "download": "Descargar",
    "print": "Imprimir",
    "filter": "Filtrar",
    "edit": "Editar",
    "save": "Guardar",
    "cancel": "Cancelar",
    "delete": "Eliminar",
    "close": "Cerrar",
    "open": "Abrir",
    "refresh": "Actualizar",
    "reset": "Restablecer",
    "submit": "Enviar",
    "confirm": "Confirmar",
    "viewDetails": "Ver detalles",
    "bulkImport": "Importación masiva",
    "all": "Todos",
    "active": "Activo",
    "inactive": "Inactivo",
    "pending": "Pendiente",
    "inProgress": "En progreso",
    "completed": "Completado",
    "paid": "Pagado",
    "partiallyPaid": "Pagado parcialmente",
    "unpaid": "No pagado",
    "overdue": "Vencido",
    "approved": "Aprobado",
    "rejected": "Rechazado",
    "toDo": "Por hacer",
    "review": "Revisión",
    "cancelled": "Cancelado",
    "high": "Alto",
    "medium": "Medio",
    "low": "Bajo",
    "urgent": "Urgente",
    "normal": "Normal",
    "dueDate": "Fecha de vencimiento",
    "priority": "Prioridad",
    "status": "Estado",
    "action": "Acción",
    "actions": "Acciones",
    "amount": "Monto",
    "date": "Fecha",
    "client": "Cliente",
    "assignee": "Asignado",
    "description": "Descripción",
    "notes": "Notas",
    "category": "Categoría",
    "type": "Tipo",
    "role": "Rol",
    "department": "Departamento",
    "salary": "Salario",
    "checkIn": "Entrada",
    "checkOut": "Salida",
    "title": "Título",
    "summary": "Resumen",
    "overview": "Visión general",
    "statistics": "Estadísticas",
    "totalRevenue": "Ingresos totales",
    "settledPayments": "Pagos liquidados",
    "activeClients": "Clientes activos",
    "pendingFees": "Honorarios pendientes",
    "totalDeliverables": "Entregables totales",
    "dailyLiveRegister": "Registro diario en vivo",
    "monthlyLeavesSalaryCuts": "Permisos mensuales y descuentos",
    "markAllPresent": "Marcar todos presentes",
    "punchIn": "Marcar entrada",
    "punchOut": "Marcar salida",
    "present": "Presente",
    "halfDay": "Medio día",
    "absent": "Ausente",
    "onLeave": "De permiso",
    "employeeName": "Nombre del empleado",
    "designatedRole": "Puesto asignado",
    "workingHours": "Horas de trabajo",
    "currentStatus": "Estado actual",
    "employeeDetails": "Detalles del empleado",
    "printDaySheet": "Imprimir hoja del día",
    "printCutsRegister": "Imprimir registro de deducciones",
    "totalStaff": "Personal total",
    "reportsAnalytics": "Informes y análisis",
    "financialReports": "Informes financieros",
    "taskReports": "Informes de tareas",
    "clientReports": "Informes de clientes",
    "attendanceSummary": "Resumen de asistencia",
    "gstSummary": "Resumen de GST",
    "tdsSummary": "Resumen de TDS",
    "outstandingFees": "Honorarios pendientes",
    "generateReport": "Generar informe",
    "viewReport": "Ver informe",
    "dateRange": "Rango de fechas",
    "fromDate": "Desde la fecha",
    "toDate": "Hasta la fecha",
    "total": "Total",
    "clientMaster": "Maestro de clientes",
    "addNewClient": "Agregar nuevo cliente",
    "allClients": "Todos los clientes",
    "taskManagement": "Gestión de tareas",
    "createTask": "Crear tarea",
    "allTasks": "Todas las tareas",
    "today": "Hoy",
    "month": "Mes",
    "week": "Semana",
    "day": "Día",
    "allTransactions": "Todas las transacciones",
    "receipts": "Recibos",
    "payments": "Pagos",
    "income": "Ingresos",
    "expense": "Gastos",
    "totalInflow": "Entradas totales",
    "totalOutflow": "Salidas totales",
    "netBalance": "Saldo neto",
    "addTransaction": "Agregar transacción",
    "invoiceNo": "N° de Factura",
    "paidAmount": "Monto pagado",
    "pendingAmount": "Monto pendiente",
    "paymentMode": "Método de pago",
    "cash": "Efectivo",
    "bankTransfer": "Transferencia bancaria",
    "upi": "UPI",
    "cheque": "Cheque",
    "receipt": "Recibo",
    "printReceipt": "Imprimir recibo",
    "firmProfile": "Perfil de la firma",
    "systemPreferences": "Preferencias del sistema",
    "userManagement": "Gestión de usuarios",
    "securityPrivacy": "Seguridad y privacidad",
    "backupRestore": "Copia de seguridad y restauración",
    "languageRegion": "Idioma y región",
    "activeSystemLanguage": "Idioma activo del sistema",
    "theme": "Tema",
    "lightMode": "Modo claro",
    "darkMode": "Modo oscuro",
    "zoomLevel": "Nivel de zoom",
    "saveChanges": "Guardar cambios",
    "updateProfile": "Actualizar perfil"
  },
  "fr": {
    "dashboard": "Tableau de bord",
    "aiStudio": "Studio IA",
    "myWork": "Mon travail",
    "clients": "Clients",
    "contactPerson": "Personne de contact",
    "projects": "Projets",
    "tasks": "Tâches",
    "taskHistory": "Historique des tâches",
    "attendance": "Présence",
    "communication": "Communication",
    "privateChat": "Chat privé",
    "askLeave": "Demande de congé",
    "leaves": "Congés",
    "teamMembers": "Membres de l'équipe",
    "departments": "Départements",
    "feesTracking": "Suivi des frais",
    "receiptsPayments": "Reçus et paiements",
    "membersPayment": "Paiement des membres",
    "membersPaymentStaff": "Paiement des membres (Personnel)",
    "ourPayment": "Notre paiement",
    "ourPaymentSalary": "Notre paiement (Mon salaire)",
    "ownerPayments": "Paiements du propriétaire",
    "reports": "Rapports",
    "activityLogs": "Journaux d'activité",
    "integrations": "Intégrations",
    "calendar": "Calendrier",
    "supportHelp": "Aide et support",
    "settings": "Paramètres",
    "editingTaskbar": "ÉDITION DE LA BARRE",
    "doneSaveTaskbar": "Terminé ✓ Enregistrer",
    "doneCheck": "Terminé ✓",
    "done": "Terminé",
    "doubleTapOrHold": "Appuyez deux fois ou maintenez pour réorganiser!",
    "moveUp": "Monter",
    "moveDown": "Descendre",
    "moveToTop": "Au sommet",
    "moveToBottom": "Tout en bas",
    "resetDefaultOrder": "Ordre par défaut",
    "holdClickDragDrop": "Glisser-déposer par clic:",
    "position": "Position",
    "slot": "Emplacement",
    "searchPlaceholder": "Rechercher par nom, raison sociale ou n° dossier",
    "search": "Recherche",
    "lockScreen": "Verrouiller l'écran",
    "privacyMode": "Verrouiller (Mode privé)",
    "profile": "Profil",
    "profileCompleted": "Profil complété",
    "profilePending": "Compléter le profil",
    "sync": "Synchroniser",
    "syncing": "Synchronisation...",
    "complaints": "Plaintes",
    "registerComplaint": "Enregistrer une plainte",
    "reportComplaint": "Signaler une plainte à la direction",
    "supportChat": "Chat de support (WhatsApp)",
    "signOut": "Déconnexion",
    "setupFirmProfile": "Configurer profil du cabinet →",
    "returnToDashboard": "Retour au tableau de bord",
    "accessRestricted": "Accès restreint",
    "addTask": "Ajouter une tâche",
    "newClient": "Nouveau client",
    "addMember": "Ajouter un membre",
    "addDepartment": "Ajouter un département",
    "applyLeave": "Poser un congé",
    "recordPayment": "Enregistrer un paiement",
    "createInvoice": "Créer une facture",
    "exportPdf": "Exporter PDF",
    "exportExcel": "Exporter Excel",
    "exportCsv": "Exporter CSV",
    "export": "Exporter",
    "download": "Télécharger",
    "print": "Imprimer",
    "filter": "Filtrer",
    "edit": "Modifier",
    "save": "Enregistrer",
    "cancel": "Annuler",
    "delete": "Supprimer",
    "close": "Fermer",
    "open": "Ouvrir",
    "refresh": "Actualiser",
    "reset": "Réinitialiser",
    "submit": "Soumettre",
    "confirm": "Confirmer",
    "viewDetails": "Voir les détails",
    "bulkImport": "Import groupé",
    "all": "Tous",
    "active": "Actif",
    "inactive": "Inactif",
    "pending": "En attente",
    "inProgress": "En cours",
    "completed": "Terminé",
    "paid": "Payé",
    "partiallyPaid": "Partiellement payé",
    "unpaid": "Non payé",
    "overdue": "En retard",
    "approved": "Approuvé",
    "rejected": "Rejeté",
    "toDo": "À faire",
    "review": "Examen",
    "cancelled": "Annulé",
    "high": "Élevé",
    "medium": "Moyen",
    "low": "Faible",
    "urgent": "Urgent",
    "normal": "Normal",
    "dueDate": "Date d'échéance",
    "priority": "Priorité",
    "status": "Statut",
    "action": "Action",
    "actions": "Actions",
    "amount": "Montant",
    "date": "Date",
    "client": "Client",
    "assignee": "Assigné",
    "description": "Description",
    "notes": "Remarques",
    "category": "Catégorie",
    "type": "Type",
    "role": "Rôle",
    "department": "Département",
    "salary": "Salaire",
    "checkIn": "Arrivée",
    "checkOut": "Départ",
    "title": "Titre",
    "summary": "Résumé",
    "overview": "Vue d'ensemble",
    "statistics": "Statistiques",
    "totalRevenue": "Revenu total",
    "settledPayments": "Paiements réglés",
    "activeClients": "Clients actifs",
    "pendingFees": "Frais en attente",
    "totalDeliverables": "Livrables totaux",
    "dailyLiveRegister": "Registre quotidien en direct",
    "monthlyLeavesSalaryCuts": "Congés mensuels et déductions",
    "markAllPresent": "Marquer tous présents",
    "punchIn": "Pointage entrée",
    "punchOut": "Pointage sortie",
    "present": "Présent",
    "halfDay": "Demi-journée",
    "absent": "Absent",
    "onLeave": "En congé",
    "employeeName": "Nom de l'employé",
    "designatedRole": "Rôle désigné",
    "workingHours": "Heures de travail",
    "currentStatus": "Statut actuel",
    "employeeDetails": "Détails de l'employé",
    "printDaySheet": "Imprimer feuille du jour",
    "printCutsRegister": "Imprimer registre déductions",
    "totalStaff": "Personnel total",
    "reportsAnalytics": "Rapports et analyses",
    "financialReports": "Rapports financiers",
    "taskReports": "Rapports de tâches",
    "clientReports": "Rapports clients",
    "attendanceSummary": "Résumé de présence",
    "gstSummary": "Résumé GST",
    "tdsSummary": "Résumé TDS",
    "outstandingFees": "Frais impayés",
    "generateReport": "Générer le rapport",
    "viewReport": "Voir le rapport",
    "dateRange": "Période",
    "fromDate": "Du",
    "toDate": "Au",
    "total": "Total",
    "clientMaster": "Fichier clients",
    "addNewClient": "Ajouter nouveau client",
    "allClients": "Tous les clients",
    "taskManagement": "Gestion des tâches",
    "createTask": "Créer une tâche",
    "allTasks": "Toutes les tâches",
    "today": "Aujourd'hui",
    "month": "Mois",
    "week": "Semaine",
    "day": "Jour",
    "allTransactions": "Toutes les transactions",
    "receipts": "Reçus",
    "payments": "Paiements",
    "income": "Revenu",
    "expense": "Dépenses",
    "totalInflow": "Entrées totales",
    "totalOutflow": "Sorties totales",
    "netBalance": "Solde net",
    "addTransaction": "Ajouter une transaction",
    "invoiceNo": "N° de facture",
    "paidAmount": "Montant payé",
    "pendingAmount": "Montant en attente",
    "paymentMode": "Mode de paiement",
    "cash": "Espèces",
    "bankTransfer": "Virement bancaire",
    "upi": "UPI",
    "cheque": "Chèque",
    "receipt": "Reçu",
    "printReceipt": "Imprimer le reçu",
    "firmProfile": "Profil du cabinet",
    "systemPreferences": "Préférences système",
    "userManagement": "Gestion des utilisateurs",
    "securityPrivacy": "Sécurité et confidentialité",
    "backupRestore": "Sauvegarde et restauration",
    "languageRegion": "Langue et région",
    "activeSystemLanguage": "Langue active du système",
    "theme": "Thème",
    "lightMode": "Mode clair",
    "darkMode": "Mode sombre",
    "zoomLevel": "Niveau de zoom",
    "saveChanges": "Enregistrer les modifications",
    "updateProfile": "Mettre à jour le profil"
  },
  "bn": {
    "dashboard": "ড্যাশবোর্ড",
    "aiStudio": "এআই স্টুডিও",
    "myWork": "আমার কাজ",
    "clients": "ক্লায়েন্ট",
    "contactPerson": "যোগাযোগকারী ব্যক্তি",
    "projects": "প্রকল্প",
    "tasks": "টাস্ক",
    "taskHistory": "কাজের ইতিহাস",
    "attendance": "উপস্থিতি",
    "communication": "যোগাযোগ",
    "privateChat": "ব্যক্তিগত চ্যাট",
    "askLeave": "ছুটির আবেদন",
    "leaves": "ছুটিসমূহ",
    "teamMembers": "দলের সদস্যরা",
    "departments": "বিভাগসমূহ",
    "feesTracking": "ফি ট্র্যাকিং",
    "receiptsPayments": "রসিদ ও পেমেন্ট",
    "membersPayment": "সদস্যদের পেমেন্ট",
    "membersPaymentStaff": "সদস্যদের পেমেন্ট (কর্মী)",
    "ourPayment": "আমাদের পেমেন্ট",
    "ourPaymentSalary": "আমাদের পেমেন্ট (আমার বেতন)",
    "ownerPayments": "মালিকের পেমেন্ট",
    "reports": "প্রতিবেদন",
    "activityLogs": "কার্যকলাপ লগ",
    "integrations": "ইন্টিগ্রেশন",
    "calendar": "ক্যালেন্ডার",
    "supportHelp": "সহায়তা ও সাহায্য",
    "settings": "সেটিংস",
    "editingTaskbar": "টাস্কবার সম্পাদনা",
    "doneSaveTaskbar": "সম্পন্ন ✓ টাস্কবার সংরক্ষণ",
    "doneCheck": "সম্পন্ন ✓",
    "done": "সম্পন্ন",
    "doubleTapOrHold": "পুনরায় সাজাতে নীচের যেকোনো উপাদানে ডাবল-ট্যাপ করুন বা চেপে ধরে রাখুন!",
    "moveUp": "উপরে সরান",
    "moveDown": "নিচে সরান",
    "moveToTop": "একদম উপরে",
    "moveToBottom": "একদম নিচে",
    "resetDefaultOrder": "ডিফল্ট ক্রম পুনরায় সেট",
    "holdClickDragDrop": "চেপে ধরে টেনে এনে ছাড়ুন:",
    "position": "অবস্থান",
    "slot": "স্লট",
    "searchPlaceholder": "নাম, ট্রেড নাম বা ফাইল নম্বর দিয়ে অনুসন্ধান করুন",
    "search": "অনুসন্ধান",
    "lockScreen": "স্ক্রিন লক করুন",
    "privacyMode": "ওয়ার্কস্পেস লক (গোপনীয়তা মোড)",
    "profile": "প্রোফাইল",
    "profileCompleted": "প্রোফাইল সম্পূর্ণ",
    "profilePending": "প্রোফাইল সম্পূর্ণ করুন",
    "sync": "সিঙ্ক",
    "syncing": "সিঙ্ক হচ্ছে...",
    "complaints": "অভিযোগ",
    "registerComplaint": "অভিযোগ দায়ের করুন",
    "reportComplaint": "ম্যানেজমেন্টে অভিযোগ করুন",
    "supportChat": "সাপোর্ট চ্যাট (হোয়াটসঅ্যাপ)",
    "signOut": "সাইন আউট",
    "setupFirmProfile": "ফার্মের প্রোফাইল সেটআপ →",
    "returnToDashboard": "ড্যাশবোর্ডে ফিরে যান",
    "accessRestricted": "অ্যাক্সেস সীমাবদ্ধ",
    "addTask": "টাস্ক যোগ করুন",
    "newClient": "নতুন ক্লায়েন্ট",
    "addMember": "সদস্য যোগ করুন",
    "addDepartment": "বিভাগ যোগ করুন",
    "applyLeave": "ছুটির আবেদন করুন",
    "recordPayment": "পেমেন্ট রেকর্ড করুন",
    "createInvoice": "চালান তৈরি করুন",
    "exportPdf": "পিডিএফ রপ্তানি",
    "exportExcel": "এক্সেল রপ্তানি",
    "exportCsv": "সিএসভি রপ্তানি",
    "export": "রপ্তানি",
    "download": "ডাউনলোড",
    "print": "মুদ্রণ",
    "filter": "ফিল্টার",
    "edit": "সম্পাদনা",
    "save": "সংরক্ষণ",
    "cancel": "বাতিল",
    "delete": "মুছুন",
    "close": "বন্ধ করুন",
    "open": "খুলুন",
    "refresh": "রিফ্রেশ",
    "reset": "রিসেট",
    "submit": "জমা দিন",
    "confirm": "নিশ্চিত করুন",
    "viewDetails": "বিস্তারিত দেখুন",
    "bulkImport": "বাল্ক আমদানি",
    "all": "সব",
    "active": "সক্রিয়",
    "inactive": "নিষ্ক্রিয়",
    "pending": "মুলতুবি",
    "inProgress": "চলমান",
    "completed": "সম্পন্ন",
    "paid": "পরিশোধিত",
    "partiallyPaid": "আংশিক পরিশোধিত",
    "unpaid": "অপরিশোধিত",
    "overdue": "মেয়াদোত্তীর্ণ",
    "approved": "অনুমোদিত",
    "rejected": "প্রত্যাখ্যাত",
    "toDo": "করণীয়",
    "review": "পর্যালোচনা",
    "cancelled": "বাতিলকৃত",
    "high": "উচ্চ",
    "medium": "মাঝারি",
    "low": "কম",
    "urgent": "জরুরি",
    "normal": "সাধারণ",
    "dueDate": "নির্দিষ্ট তারিখ",
    "priority": "অগ্রাধিকার",
    "status": "অবস্থা",
    "action": "পদক্ষেপ",
    "actions": "পদক্ষেপসমূহ",
    "amount": "পরিমাণ",
    "date": "তারিখ",
    "client": "ক্লায়েন্ট",
    "assignee": "নিয়োজিত ব্যক্তি",
    "description": "বিবরণ",
    "notes": "নোট",
    "category": "বিভাগ",
    "type": "ধরন",
    "role": "ভূমিকা",
    "department": "বিভাগ",
    "salary": "বেতন",
    "checkIn": "চেক ইন",
    "checkOut": "চেક আউট",
    "title": "শিরোনাম",
    "summary": "সারসংক্ষেপ",
    "overview": "এক নজরে",
    "statistics": "পরিসংখ্যান",
    "totalRevenue": "মোট আয়",
    "settledPayments": "নিষ্পত্তিকৃত পেমেন্ট",
    "activeClients": "সক্রিয় ক্লায়েন্ট",
    "pendingFees": "বকেয়া ফি",
    "totalDeliverables": "মোট ডেলিভারেবল",
    "dailyLiveRegister": "দৈনিক লাইভ রেজিস্টার",
    "monthlyLeavesSalaryCuts": "মাসিক ছুটি ও বেতন কর্তন",
    "markAllPresent": "সবাইকে উপস্থিত চিহ্নিত করুন",
    "punchIn": "পাঞ্চ-ইন",
    "punchOut": "পাঞ্চ-আউট",
    "present": "উপস্থিত",
    "halfDay": "অর্ধ দিবস",
    "absent": "অনুপস্থিত",
    "onLeave": "ছুটিতে",
    "employeeName": "কর্মচারীর নাম",
    "designatedRole": "নির্ধারিত পদ",
    "workingHours": "কাজের সময়",
    "currentStatus": "বর্তমান অবস্থা",
    "employeeDetails": "কর্মচারীর বিবরণ",
    "printDaySheet": "দিনের শীট মুদ্রণ",
    "printCutsRegister": "কর্তন রেজিস্টার মুদ্রণ",
    "totalStaff": "মোট কর্মী",
    "reportsAnalytics": "প্রতিবেদন ও বিশ্লেষণ",
    "financialReports": "আর্থিক প্রতিবেদন",
    "taskReports": "কাজের প্রতিবেদন",
    "clientReports": "ক্লায়েন্ট প্রতিবেদন",
    "attendanceSummary": "উপস্থিতির সারসংক্ষেপ",
    "gstSummary": "জিএসটি সারসংক্ষেপ",
    "tdsSummary": "টিডিএস সারসংক্ষেপ",
    "outstandingFees": "বকেয়া ফি",
    "generateReport": "প্রতিবেদন তৈরি করুন",
    "viewReport": "প্রতিবেদন দেখুন",
    "dateRange": "তারিখের পরিসীমা",
    "fromDate": "তারিখ হতে",
    "toDate": "তারিখ পর্যন্ত",
    "total": "মোট",
    "clientMaster": "ক্লায়েন্ট মাস্টার",
    "addNewClient": "নতুন ক্লায়েন্ট যোগ করুন",
    "allClients": "সকল ক্লায়েন্ট",
    "taskManagement": "টাস্ক পরিচালনা",
    "createTask": "টাস্ক তৈরি করুন",
    "allTasks": "সকল টাস্ক",
    "today": "আজ",
    "month": "মাস",
    "week": "সপ্তাহ",
    "day": "দিন",
    "allTransactions": "সকল লেনদেন",
    "receipts": "রসিদ",
    "payments": "পেমেন্ট",
    "income": "আয়",
    "expense": "ব্যয়",
    "totalInflow": "মোট অন্তর্বাহ",
    "totalOutflow": "মোট বহির্গমন",
    "netBalance": "নিট ব্যালেন্স",
    "addTransaction": "লেনদেন যোগ করুন",
    "invoiceNo": "চালান নম্বর",
    "paidAmount": "পরিশোধিত অর্থ",
    "pendingAmount": "বকেয়া পরিমাণ",
    "paymentMode": "পেমেন্ট পদ্ধতি",
    "cash": "নগদ",
    "bankTransfer": "ব্যাংক স্থানান্তর",
    "upi": "ইউপিআই",
    "cheque": "চেক",
    "receipt": "রসিদ",
    "printReceipt": "রসিদ মুদ্রণ করুন",
    "firmProfile": "ফার্মের প্রোফাইল",
    "systemPreferences": "সিস্টেম পছন্দসমূহ",
    "userManagement": "ব্যবহারকারী পরিচালনা",
    "securityPrivacy": "নিরাপত্তা ও গোপনীয়তা",
    "backupRestore": "ব্যাকআপ ও পুনরুদ্ধার",
    "languageRegion": "ভাষা ও অঞ্চল",
    "activeSystemLanguage": "সক্রিয় সিস্টেমের ভাষা",
    "theme": "থিম",
    "lightMode": "লাইট মোড",
    "darkMode": "ডার্ক মোড",
    "zoomLevel": "জুম লেভেল",
    "saveChanges": "পরিবর্তন সংরক্ষণ করুন",
    "updateProfile": "প্রোফাইল আপডেট"
  },
  "de": {
    "dashboard": "Übersicht",
    "aiStudio": "KI-Studio",
    "myWork": "Meine Arbeit",
    "clients": "Kunden",
    "contactPerson": "Ansprechpartner",
    "projects": "Projekte",
    "tasks": "Aufgaben",
    "taskHistory": "Aufgabenverlauf",
    "attendance": "Anwesenheit",
    "communication": "Kommunikation",
    "privateChat": "Privater Chat",
    "askLeave": "Urlaub beantragen",
    "leaves": "Urlaubstage",
    "teamMembers": "Teammitglieder",
    "departments": "Abteilungen",
    "feesTracking": "Gebührenverfolgung",
    "receiptsPayments": "Einnahmen & Zahlungen",
    "membersPayment": "Mitarbeiterzahlungen",
    "membersPaymentStaff": "Mitarbeitervergütung (Personal)",
    "ourPayment": "Unsere Zahlung",
    "ourPaymentSalary": "Unsere Zahlung (Mein Gehalt)",
    "ownerPayments": "Inhaberzahlungen",
    "reports": "Berichte",
    "activityLogs": "Aktivitätsprotokolle",
    "integrations": "Integrationen",
    "calendar": "Kalender",
    "supportHelp": "Support & Hilfe",
    "settings": "Einstellungen",
    "editingTaskbar": "TASKLEISTE BEARBEITEN",
    "doneSaveTaskbar": "Fertig ✓ Leiste speichern",
    "doneCheck": "Fertig ✓",
    "done": "Fertig",
    "doubleTapOrHold": "Doppeltippen oder gedrückt halten zum Neuanordnen!",
    "moveUp": "Nach oben",
    "moveDown": "Nach unten",
    "moveToTop": "Ganz nach oben",
    "moveToBottom": "Ganz nach unten",
    "resetDefaultOrder": "Standardreihenfolge",
    "holdClickDragDrop": "Gedrückt halten & ziehen:",
    "position": "Position",
    "slot": "Platz",
    "searchPlaceholder": "Nach Name, Firma oder Aktennr. suchen",
    "search": "Suchen",
    "lockScreen": "Bildschirm sperren",
    "privacyMode": "Arbeitsbereich sperren (Datenschutz)",
    "profile": "Profil",
    "profileCompleted": "Profil ausgefüllt",
    "profilePending": "Profil vervollständigen",
    "sync": "Sync",
    "syncing": "Synchronisiere...",
    "complaints": "Beschwerden",
    "registerComplaint": "Beschwerde einreichen",
    "reportComplaint": "Beschwerde an Geschäftsleitung melden",
    "supportChat": "Support-Chat (WhatsApp)",
    "signOut": "Abmelden",
    "setupFirmProfile": "Kanzleiprofil einrichten →",
    "returnToDashboard": "Zurück zur Übersicht",
    "accessRestricted": "Zugriff beschränkt",
    "addTask": "Aufgabe hinzufügen",
    "newClient": "Neuer Kunde",
    "addMember": "Mitglied hinzufügen",
    "addDepartment": "Abteilung hinzufügen",
    "applyLeave": "Urlaub einreichen",
    "recordPayment": "Zahlung erfassen",
    "createInvoice": "Rechnung erstellen",
    "exportPdf": "PDF exportieren",
    "exportExcel": "Excel exportieren",
    "exportCsv": "CSV exportieren",
    "export": "Exportieren",
    "download": "Herunterladen",
    "print": "Drucken",
    "filter": "Filtern",
    "edit": "Bearbeiten",
    "save": "Speichern",
    "cancel": "Abbrechen",
    "delete": "Löschen",
    "close": "Schließen",
    "open": "Öffnen",
    "refresh": "Aktualisieren",
    "reset": "Zurücksetzen",
    "submit": "Absenden",
    "confirm": "Bestätigen",
    "viewDetails": "Details anzeigen",
    "bulkImport": "Massenimport",
    "all": "Alle",
    "active": "Aktiv",
    "inactive": "Inaktiv",
    "pending": "Ausstehend",
    "inProgress": "In Bearbeitung",
    "completed": "Abgeschlossen",
    "paid": "Bezahlt",
    "partiallyPaid": "Teilweise bezahlt",
    "unpaid": "Unbezahlt",
    "overdue": "Überfällig",
    "approved": "Genehmigt",
    "rejected": "Abgelehnt",
    "toDo": "Zu erledigen",
    "review": "Überprüfung",
    "cancelled": "Storniert",
    "high": "Hoch",
    "medium": "Mittel",
    "low": "Niedrig",
    "urgent": "Dringend",
    "normal": "Normal",
    "dueDate": "Fälligkeitsdatum",
    "priority": "Priorität",
    "status": "Status",
    "action": "Aktion",
    "actions": "Aktionen",
    "amount": "Betrag",
    "date": "Datum",
    "client": "Kunde",
    "assignee": "Zugewiesener",
    "description": "Beschreibung",
    "notes": "Notizen",
    "category": "Kategorie",
    "type": "Typ",
    "role": "Rolle",
    "department": "Abteilung",
    "salary": "Gehalt",
    "checkIn": "Kommen",
    "checkOut": "Gehen",
    "title": "Titel",
    "summary": "Zusammenfassung",
    "overview": "Überblick",
    "statistics": "Statistiken",
    "totalRevenue": "Gesamtumsatz",
    "settledPayments": "Abgerechnete Zahlungen",
    "activeClients": "Aktive Kunden",
    "pendingFees": "Ausstehende Gebühren",
    "totalDeliverables": "Gesamtergebnisse",
    "dailyLiveRegister": "Tägliches Live-Register",
    "monthlyLeavesSalaryCuts": "Monatlicher Urlaub & Gehaltsabzüge",
    "markAllPresent": "Alle als anwesend markieren",
    "punchIn": "Einchecken",
    "punchOut": "Auschecken",
    "present": "Anwesend",
    "halfDay": "Halber Tag",
    "absent": "Abwesend",
    "onLeave": "Im Urlaub",
    "employeeName": "Mitarbeitername",
    "designatedRole": "Vorgesehene Rolle",
    "workingHours": "Arbeitsstunden",
    "currentStatus": "Aktueller Status",
    "employeeDetails": "Mitarbeiterdetails",
    "printDaySheet": "Tagesblatt drucken",
    "printCutsRegister": "Abzugsregister drucken",
    "totalStaff": "Gesamtpersonal",
    "reportsAnalytics": "Berichte & Analysen",
    "financialReports": "Finanzberichte",
    "taskReports": "Aufgabenberichte",
    "clientReports": "Kundenberichte",
    "attendanceSummary": "Anwesenheitsübersicht",
    "gstSummary": "GST-Übersicht",
    "tdsSummary": "TDS-Übersicht",
    "outstandingFees": "Ausstehende Gebühren",
    "generateReport": "Bericht erstellen",
    "viewReport": "Bericht anzeigen",
    "dateRange": "Datumsbereich",
    "fromDate": "Von Datum",
    "toDate": "Bis Datum",
    "total": "Gesamt",
    "clientMaster": "Kundenstamm",
    "addNewClient": "Neuen Kunden anlegen",
    "allClients": "Alle Kunden",
    "taskManagement": "Aufgabenmanagement",
    "createTask": "Aufgabe erstellen",
    "allTasks": "Alle Aufgaben",
    "today": "Heute",
    "month": "Monat",
    "week": "Woche",
    "day": "Tag",
    "allTransactions": "Alle Transaktionen",
    "receipts": "Einnahmen",
    "payments": "Zahlungen",
    "income": "Einnahme",
    "expense": "Ausgabe",
    "totalInflow": "Gesamteinnahmen",
    "totalOutflow": "Gesamtausgaben",
    "netBalance": "Nettosaldo",
    "addTransaction": "Transaktion hinzufügen",
    "invoiceNo": "Rechnungsnr.",
    "paidAmount": "Gezahlter Betrag",
    "pendingAmount": "Ausstehender Betrag",
    "paymentMode": "Zahlungsart",
    "cash": "Bargeld",
    "bankTransfer": "Banküberweisung",
    "upi": "UPI",
    "cheque": "Scheck",
    "receipt": "Quittung",
    "printReceipt": "Quittung drucken",
    "firmProfile": "Kanzleiprofil",
    "systemPreferences": "Systemeinstellungen",
    "userManagement": "Benutzerverwaltung",
    "securityPrivacy": "Sicherheit & Datenschutz",
    "backupRestore": "Sicherung & Wiederherstellung",
    "languageRegion": "Sprache & Region",
    "activeSystemLanguage": "Aktive Systemsprache",
    "theme": "Design",
    "lightMode": "Heller Modus",
    "darkMode": "Dunkler Modus",
    "zoomLevel": "Zoomstufe",
    "saveChanges": "Änderungen speichern",
    "updateProfile": "Profil aktualisieren"
  },
  "pt": {
    "dashboard": "Painel",
    "aiStudio": "Estúdio de IA",
    "myWork": "Meu Trabalho",
    "clients": "Clientes",
    "contactPerson": "Pessoa de Contato",
    "projects": "Projetos",
    "tasks": "Tarefas",
    "taskHistory": "Histórico de Tarefas",
    "attendance": "Presença",
    "communication": "Comunicação",
    "privateChat": "Chat Privado",
    "askLeave": "Pedir Folga",
    "leaves": "Licenças",
    "teamMembers": "Membros da Equipe",
    "departments": "Departamentos",
    "feesTracking": "Rastreamento de Taxas",
    "receiptsPayments": "Recibos e Pagamentos",
    "membersPayment": "Pagamento de Membros",
    "membersPaymentStaff": "Pagamento de Membros (Equipe)",
    "ourPayment": "Nosso Pagamento",
    "ourPaymentSalary": "Nosso Pagamento (Meu Salário)",
    "ownerPayments": "Pagamentos do Proprietário",
    "reports": "Relatórios",
    "activityLogs": "Registros de Atividade",
    "integrations": "Integrações",
    "calendar": "Calendário",
    "supportHelp": "Suporte e Ajuda",
    "settings": "Configurações",
    "editingTaskbar": "EDITANDO BARRA",
    "doneSaveTaskbar": "Concluído ✓ Salvar Barra",
    "doneCheck": "Concluído ✓",
    "done": "Concluído",
    "doubleTapOrHold": "Toque duas vezes ou segure qualquer item para reordenar!",
    "moveUp": "Mover para Cima",
    "moveDown": "Mover para Baixo",
    "moveToTop": "Mover para o Topo",
    "moveToBottom": "Mover para o Fim",
    "resetDefaultOrder": "Ordem Padrão",
    "holdClickDragDrop": "Segurar e arrastar:",
    "position": "Posição",
    "slot": "Vaga",
    "searchPlaceholder": "Pesquisar por Nome, Razão Social ou Arquivo",
    "search": "Buscar",
    "lockScreen": "Bloquear Tela",
    "privacyMode": "Bloquear Área (Modo Privacidade)",
    "profile": "Perfil",
    "profileCompleted": "Perfil Concluído",
    "profilePending": "Completar Perfil",
    "sync": "Sincronizar",
    "syncing": "Sincronizando...",
    "complaints": "Reclamações",
    "registerComplaint": "Registrar Reclamação",
    "reportComplaint": "Reportar Reclamação à Gestão",
    "supportChat": "Chat de Suporte (WhatsApp)",
    "signOut": "Sair",
    "setupFirmProfile": "Configurar Perfil da Empresa →",
    "returnToDashboard": "Voltar ao Painel",
    "accessRestricted": "Acesso Restrito",
    "addTask": "Adicionar Tarefa",
    "newClient": "Novo Cliente",
    "addMember": "Adicionar Membro",
    "addDepartment": "Adicionar Departamento",
    "applyLeave": "Solicitar Licença",
    "recordPayment": "Registrar Pagamento",
    "createInvoice": "Criar Fatura",
    "exportPdf": "Exportar PDF",
    "exportExcel": "Exportar Excel",
    "exportCsv": "Exportar CSV",
    "export": "Exportar",
    "download": "Baixar",
    "print": "Imprimir",
    "filter": "Filtrar",
    "edit": "Editar",
    "save": "Salvar",
    "cancel": "Cancelar",
    "delete": "Excluir",
    "close": "Fechar",
    "open": "Abrir",
    "refresh": "Atualizar",
    "reset": "Redefinir",
    "submit": "Enviar",
    "confirm": "Confirmar",
    "viewDetails": "Ver Detalhes",
    "bulkImport": "Importação em Massa",
    "all": "Todos",
    "active": "Ativo",
    "inactive": "Inativo",
    "pending": "Pendente",
    "inProgress": "Em Andamento",
    "completed": "Concluído",
    "paid": "Pago",
    "partiallyPaid": "Parcialmente Pago",
    "unpaid": "Não Pago",
    "overdue": "Atrasado",
    "approved": "Aprovado",
    "rejected": "Rejeitado",
    "toDo": "A Fazer",
    "review": "Revisão",
    "cancelled": "Cancelado",
    "high": "Alto",
    "medium": "Médio",
    "low": "Baixo",
    "urgent": "Urgente",
    "normal": "Normal",
    "dueDate": "Data de Vencimento",
    "priority": "Prioridade",
    "status": "Status",
    "action": "Ação",
    "actions": "Ações",
    "amount": "Valor",
    "date": "Data",
    "client": "Cliente",
    "assignee": "Responsável",
    "description": "Descrição",
    "notes": "Notas",
    "category": "Categoria",
    "type": "Tipo",
    "role": "Função",
    "department": "Departamento",
    "salary": "Salário",
    "checkIn": "Entrada",
    "checkOut": "Saída",
    "title": "Título",
    "summary": "Resumo",
    "overview": "Visão Geral",
    "statistics": "Estatísticas",
    "totalRevenue": "Receita Total",
    "settledPayments": "Pagamentos Liquidados",
    "activeClients": "Clientes Ativos",
    "pendingFees": "Taxas Pendentes",
    "totalDeliverables": "Total de Entregas",
    "dailyLiveRegister": "Registro Diário ao Vivo",
    "monthlyLeavesSalaryCuts": "Licenças Mensais e Descontos",
    "markAllPresent": "Marcar Todos como Presentes",
    "punchIn": "Bater Ponto (Entrada)",
    "punchOut": "Bater Ponto (Saída)",
    "present": "Presente",
    "halfDay": "Meio Período",
    "absent": "Ausente",
    "onLeave": "De Licença",
    "employeeName": "Nome do Funcionário",
    "designatedRole": "Função Designada",
    "workingHours": "Horas Trabalhadas",
    "currentStatus": "Status Atual",
    "employeeDetails": "Detalhes do Funcionário",
    "printDaySheet": "Imprimir Folha do Dia",
    "printCutsRegister": "Imprimir Registro de Cortes",
    "totalStaff": "Total da Equipe",
    "reportsAnalytics": "Relatórios e Análises",
    "financialReports": "Relatórios Financeiros",
    "taskReports": "Relatórios de Tarefas",
    "clientReports": "Relatórios de Clientes",
    "attendanceSummary": "Resumo de Presença",
    "gstSummary": "Resumo de GST",
    "tdsSummary": "Resumo de TDS",
    "outstandingFees": "Taxas Pendentes",
    "generateReport": "Gerar Relatório",
    "viewReport": "Ver Relatório",
    "dateRange": "Intervalo de Datas",
    "fromDate": "Data Inicial",
    "toDate": "Data Final",
    "total": "Total",
    "clientMaster": "Cadastro de Clientes",
    "addNewClient": "Adicionar Novo Cliente",
    "allClients": "Todos os Clientes",
    "taskManagement": "Gestão de Tarefas",
    "createTask": "Criar Tarefa",
    "allTasks": "Todas as Tarefas",
    "today": "Hoje",
    "month": "Mês",
    "week": "Semana",
    "day": "Dia",
    "allTransactions": "Todas as Transações",
    "receipts": "Recibos",
    "payments": "Pagamentos",
    "income": "Renda",
    "expense": "Despesa",
    "totalInflow": "Entrada Total",
    "totalOutflow": "Saída Total",
    "netBalance": "Saldo Líquido",
    "addTransaction": "Adicionar Transação",
    "invoiceNo": "Nº da Fatura",
    "paidAmount": "Valor Pago",
    "pendingAmount": "Valor Pendente",
    "paymentMode": "Forma de Pagamento",
    "cash": "Dinheiro",
    "bankTransfer": "Transferência Bancária",
    "upi": "UPI",
    "cheque": "Cheque",
    "receipt": "Recibo",
    "printReceipt": "Imprimir Recibo",
    "firmProfile": "Perfil da Empresa",
    "systemPreferences": "Preferências do Sistema",
    "userManagement": "Gerenciamento de Usuários",
    "securityPrivacy": "Segurança e Privacidade",
    "backupRestore": "Backup e Restauração",
    "languageRegion": "Idioma e Região",
    "activeSystemLanguage": "Idioma Ativo do Sistema",
    "theme": "Tema",
    "lightMode": "Modo Claro",
    "darkMode": "Modo Escuro",
    "zoomLevel": "Nível de Zoom",
    "saveChanges": "Salvar Alterações",
    "updateProfile": "Atualizar Perfil"
  },
  "zh": {
    "dashboard": "仪表板",
    "aiStudio": "AI 工作室",
    "myWork": "我的工作",
    "clients": "客户",
    "contactPerson": "联系人",
    "projects": "项目",
    "tasks": "任务",
    "taskHistory": "任务历史",
    "attendance": "考勤",
    "communication": "沟通",
    "privateChat": "私聊",
    "askLeave": "请假申请",
    "leaves": "假期",
    "teamMembers": "团队成员",
    "departments": "部门",
    "feesTracking": "费用追踪",
    "receiptsPayments": "收据与付款",
    "membersPayment": "成员付款",
    "membersPaymentStaff": "成员付款（员工）",
    "ourPayment": "我们的付款",
    "ourPaymentSalary": "我们的付款（我的薪资）",
    "ownerPayments": "业主付款",
    "reports": "报表",
    "activityLogs": "活动日志",
    "integrations": "集成",
    "calendar": "日历",
    "supportHelp": "支持与帮助",
    "settings": "设置",
    "editingTaskbar": "正在编辑任务栏",
    "doneSaveTaskbar": "完成 ✓ 保存任务栏",
    "doneCheck": "完成 ✓",
    "done": "完成",
    "doubleTapOrHold": "双击或长按以下任意项目即可重新排序！",
    "moveUp": "上移",
    "moveDown": "下移",
    "moveToTop": "移到顶部",
    "moveToBottom": "移到底部",
    "resetDefaultOrder": "恢复默认顺序",
    "holdClickDragDrop": "按住拖放：",
    "position": "位置",
    "slot": "槽位",
    "searchPlaceholder": "按姓名、商号或档案号搜索",
    "search": "搜索",
    "lockScreen": "锁定屏幕",
    "privacyMode": "锁定工作区（隐私模式）",
    "profile": "个人资料",
    "profileCompleted": "资料已完善",
    "profilePending": "完善资料",
    "sync": "同步",
    "syncing": "同步中...",
    "complaints": "投诉建议",
    "registerComplaint": "登记投诉",
    "reportComplaint": "向管理层报告投诉",
    "supportChat": "客服聊天（WhatsApp）",
    "signOut": "退出登录",
    "setupFirmProfile": "设置事务所资料 →",
    "returnToDashboard": "返回仪表板",
    "accessRestricted": "访问受限",
    "addTask": "添加任务",
    "newClient": "新建客户",
    "addMember": "添加成员",
    "addDepartment": "添加部门",
    "applyLeave": "申请休假",
    "recordPayment": "记录付款",
    "createInvoice": "创建发票",
    "exportPdf": "导出 PDF",
    "exportExcel": "导出 Excel",
    "exportCsv": "导出 CSV",
    "export": "导出",
    "download": "下载",
    "print": "打印",
    "filter": "筛选",
    "edit": "编辑",
    "save": "保存",
    "cancel": "取消",
    "delete": "删除",
    "close": "关闭",
    "open": "打开",
    "refresh": "刷新",
    "reset": "重置",
    "submit": "提交",
    "confirm": "确认",
    "viewDetails": "查看详情",
    "bulkImport": "批量导入",
    "all": "全部",
    "active": "有效",
    "inactive": "停用",
    "pending": "待处理",
    "inProgress": "进行中",
    "completed": "已完成",
    "paid": "已付",
    "partiallyPaid": "部分付款",
    "unpaid": "未付",
    "overdue": "逾期",
    "approved": "已批准",
    "rejected": "已拒绝",
    "toDo": "待办",
    "review": "审核",
    "cancelled": "已取消",
    "high": "高",
    "medium": "中",
    "low": "低",
    "urgent": "紧急",
    "normal": "普通",
    "dueDate": "截止日期",
    "priority": "优先级",
    "status": "状态",
    "action": "操作",
    "actions": "操作",
    "amount": "金额",
    "date": "日期",
    "client": "客户",
    "assignee": "经办人",
    "description": "描述",
    "notes": "备注",
    "category": "类别",
    "type": "类型",
    "role": "角色",
    "department": "部门",
    "salary": "工资",
    "checkIn": "签到",
    "checkOut": "签退",
    "title": "标题",
    "summary": "总结",
    "overview": "概览",
    "statistics": "统计",
    "totalRevenue": "总收入",
    "settledPayments": "已结付款",
    "activeClients": "活跃客户",
    "pendingFees": "待收费用",
    "totalDeliverables": "总交付成果",
    "dailyLiveRegister": "每日实时花名册",
    "monthlyLeavesSalaryCuts": "月度休假与薪资扣除",
    "markAllPresent": "全部标记出勤",
    "punchIn": "打卡上班",
    "punchOut": "打卡下班",
    "present": "出勤",
    "halfDay": "半天",
    "absent": "缺勤",
    "onLeave": "休假中",
    "employeeName": "员工姓名",
    "designatedRole": "指定角色",
    "workingHours": "工作时间",
    "currentStatus": "当前状态",
    "employeeDetails": "员工详情",
    "printDaySheet": "打印日报表",
    "printCutsRegister": "打印扣款名册",
    "totalStaff": "员工总数",
    "reportsAnalytics": "报表与分析",
    "financialReports": "财务报表",
    "taskReports": "任务报表",
    "clientReports": "客户报表",
    "attendanceSummary": "考勤摘要",
    "gstSummary": "GST 摘要",
    "tdsSummary": "TDS 摘要",
    "outstandingFees": "未收费用",
    "generateReport": "生成报表",
    "viewReport": "查看报表",
    "dateRange": "日期范围",
    "fromDate": "起始日期",
    "toDate": "截止日期",
    "total": "合计",
    "clientMaster": "客户总表",
    "addNewClient": "添加新客户",
    "allClients": "所有客户",
    "taskManagement": "任务管理",
    "createTask": "创建任务",
    "allTasks": "所有任务",
    "today": "今天",
    "month": "月份",
    "week": "周",
    "day": "日",
    "allTransactions": "所有交易",
    "receipts": "收入凭单",
    "payments": "付款",
    "income": "收入",
    "expense": "支出",
    "totalInflow": "总流入",
    "totalOutflow": "总流出",
    "netBalance": "净余额",
    "addTransaction": "添加交易",
    "invoiceNo": "发票号码",
    "paidAmount": "已付金额",
    "pendingAmount": "待付金额",
    "paymentMode": "支付方式",
    "cash": "现金",
    "bankTransfer": "银行转账",
    "upi": "UPI",
    "cheque": "支票",
    "receipt": "收据",
    "printReceipt": "打印收据",
    "firmProfile": "事务所资料",
    "systemPreferences": "系统首选项",
    "userManagement": "用户管理",
    "securityPrivacy": "安全与隐私",
    "backupRestore": "备份与恢复",
    "languageRegion": "语言与地区",
    "activeSystemLanguage": "当前系统语言",
    "theme": "主题",
    "lightMode": "浅色模式",
    "darkMode": "深色模式",
    "zoomLevel": "缩放比例",
    "saveChanges": "保存修改",
    "updateProfile": "更新个人信息"
  },
  "ja": {
    "dashboard": "ダッシュボード",
    "aiStudio": "AI スタジオ",
    "myWork": "マイワーク",
    "clients": "クライアント",
    "contactPerson": "担当者",
    "projects": "プロジェクト",
    "tasks": "タスク",
    "taskHistory": "タスク履歴",
    "attendance": "勤怠",
    "communication": "コミュニケーション",
    "privateChat": "プライベートチャット",
    "askLeave": "休暇申請",
    "leaves": "休暇管理",
    "teamMembers": "チームメンバー",
    "departments": "部門",
    "feesTracking": "料金管理",
    "receiptsPayments": "入出金管理",
    "membersPayment": "メンバー支払い",
    "membersPaymentStaff": "メンバー支払い（スタッフ）",
    "ourPayment": "自己支払い",
    "ourPaymentSalary": "自己支払い（給与）",
    "ownerPayments": "オーナー支払い",
    "reports": "レポート",
    "activityLogs": "活動ログ",
    "integrations": "外部連携",
    "calendar": "カレンダー",
    "supportHelp": "サポート＆ヘルプ",
    "settings": "設定",
    "editingTaskbar": "タスクバー編集中",
    "doneSaveTaskbar": "完了 ✓ タスクバー保存",
    "doneCheck": "完了 ✓",
    "done": "完了",
    "doubleTapOrHold": "並べ替えるには、下の項目をダブルタップまたは長押ししてください！",
    "moveUp": "上へ移動",
    "moveDown": "下へ移動",
    "moveToTop": "先頭へ移動",
    "moveToBottom": "末尾へ移動",
    "resetDefaultOrder": "初期順序に戻す",
    "holdClickDragDrop": "長押しドラッグ＆ドロップ：",
    "position": "位置",
    "slot": "スロット",
    "searchPlaceholder": "氏名、商号、ファイル番号で検索",
    "search": "検索",
    "lockScreen": "画面ロック",
    "privacyMode": "ワークスペースロック（プライバシー）",
    "profile": "プロフィール",
    "profileCompleted": "プロフ完了",
    "profilePending": "プロフ設定",
    "sync": "同期",
    "syncing": "同期中...",
    "complaints": "苦情・要望",
    "registerComplaint": "苦情を登録",
    "reportComplaint": "経営陣へ報告",
    "supportChat": "サポートチャット（WhatsApp）",
    "signOut": "サインアウト",
    "setupFirmProfile": "法人プロファイル設定 →",
    "returnToDashboard": "ダッシュボードに戻る",
    "accessRestricted": "アクセス制限",
    "addTask": "タスク追加",
    "newClient": "新規顧客",
    "addMember": "メンバー追加",
    "addDepartment": "部門追加",
    "applyLeave": "休暇届提出",
    "recordPayment": "支払い記録",
    "createInvoice": "請求書作成",
    "exportPdf": "PDF エクスポート",
    "exportExcel": "Excel エクスポート",
    "exportCsv": "CSV エクスポート",
    "export": "エクスポート",
    "download": "ダウンロード",
    "print": "印刷",
    "filter": "フィルター",
    "edit": "編集",
    "save": "保存",
    "cancel": "キャンセル",
    "delete": "削除",
    "close": "閉じる",
    "open": "開く",
    "refresh": "更新",
    "reset": "リセット",
    "submit": "送信",
    "confirm": "確認",
    "viewDetails": "詳細を見る",
    "bulkImport": "一括インポート",
    "all": "すべて",
    "active": "有効",
    "inactive": "無効",
    "pending": "保留中",
    "inProgress": "進行中",
    "completed": "完了",
    "paid": "支払済",
    "partiallyPaid": "一部入金",
    "unpaid": "未払い",
    "overdue": "期限超過",
    "approved": "承認済",
    "rejected": "却下",
    "toDo": "未着手",
    "review": "レビュー",
    "cancelled": "キャンセル済",
    "high": "高",
    "medium": "中",
    "low": "低",
    "urgent": "緊急",
    "normal": "通常",
    "dueDate": "期日",
    "priority": "優先度",
    "status": "ステータス",
    "action": "アクション",
    "actions": "操作",
    "amount": "金額",
    "date": "日付",
    "client": "顧客",
    "assignee": "担当者",
    "description": "説明",
    "notes": "メモ",
    "category": "カテゴリー",
    "type": "タイプ",
    "role": "ロール",
    "department": "部署",
    "salary": "給与",
    "checkIn": "出勤",
    "checkOut": "退勤",
    "title": "タイトル",
    "summary": "サマリー",
    "overview": "概要",
    "statistics": "統計",
    "totalRevenue": "総収益",
    "settledPayments": "決済済支払",
    "activeClients": "有効顧客",
    "pendingFees": "未収料金",
    "totalDeliverables": "総納品物",
    "dailyLiveRegister": "出勤簿",
    "monthlyLeavesSalaryCuts": "月次休暇・控除",
    "markAllPresent": "全員出席にする",
    "punchIn": "出勤打刻",
    "punchOut": "退勤打刻",
    "present": "出席",
    "halfDay": "半日",
    "absent": "欠勤",
    "onLeave": "休暇中",
    "employeeName": "従業員氏名",
    "designatedRole": "役職",
    "workingHours": "労働時間",
    "currentStatus": "現在の状況",
    "employeeDetails": "従業員詳細",
    "printDaySheet": "日報印刷",
    "printCutsRegister": "控除帳票印刷",
    "totalStaff": "全職員",
    "reportsAnalytics": "レポートと分析",
    "financialReports": "財務レポート",
    "taskReports": "タスクレポート",
    "clientReports": "顧客レポート",
    "attendanceSummary": "勤怠サマリー",
    "gstSummary": "GST サマリー",
    "tdsSummary": "TDS サマリー",
    "outstandingFees": "未払手数料",
    "generateReport": "レポート生成",
    "viewReport": "レポート表示",
    "dateRange": "期間指定",
    "fromDate": "開始日",
    "toDate": "終了日",
    "total": "合計",
    "clientMaster": "顧客マスタ",
    "addNewClient": "新規顧客追加",
    "allClients": "全顧客",
    "taskManagement": "タスク管理",
    "createTask": "タスク作成",
    "allTasks": "全タスク",
    "today": "今日",
    "month": "月",
    "week": "週",
    "day": "日",
    "allTransactions": "全取引",
    "receipts": "領収証",
    "payments": "支払",
    "income": "収入",
    "expense": "支出",
    "totalInflow": "総入金",
    "totalOutflow": "総出金",
    "netBalance": "純残高",
    "addTransaction": "取引追加",
    "invoiceNo": "請求書番号",
    "paidAmount": "支払済金額",
    "pendingAmount": "未払金額",
    "paymentMode": "支払方法",
    "cash": "現金",
    "bankTransfer": "銀行振込",
    "upi": "UPI",
    "cheque": "小切手",
    "receipt": "領収書",
    "printReceipt": "領収書印刷",
    "firmProfile": "企業情報",
    "systemPreferences": "システム設定",
    "userManagement": "ユーザー管理",
    "securityPrivacy": "セキュリティとプライバシー",
    "backupRestore": "バックアップと復元",
    "languageRegion": "言語と地域",
    "activeSystemLanguage": "システム稼働言語",
    "theme": "テーマ",
    "lightMode": "ライトモード",
    "darkMode": "ダークモード",
    "zoomLevel": "ズーム倍率",
    "saveChanges": "変更を保存",
    "updateProfile": "プロフ更新"
  }
};

export const getActiveLanguage = () => {
  if (typeof window === 'undefined') return SUPPORTED_LANGUAGES[0];
  try {
    const saved = localStorage.getItem('taxpro_language');
    const match = SUPPORTED_LANGUAGES.find(l => l.code === saved);
    return match || SUPPORTED_LANGUAGES[0];
  } catch (e) {
    return SUPPORTED_LANGUAGES[0];
  }
};

// Fast Omnidirectional Reverse Lookup Map indexing all 12 languages
let omniReverseMap = null;
export function getReverseLookupMap() {
  if (omniReverseMap) return omniReverseMap;
  omniReverseMap = new Map();

  for (const [langCode, dict] of Object.entries(TRANSLATIONS)) {
    for (const [key, text] of Object.entries(dict)) {
      if (text && typeof text === 'string') {
        const clean = text.toLowerCase().trim();
        if (clean) {
          omniReverseMap.set(clean, key);
          const stripped = clean.replace(/[:.✓→←*•#…]+/g, '').trim();
          if (stripped && stripped !== clean) {
            omniReverseMap.set(stripped, key);
          }
        }
      }
    }
  }
  return omniReverseMap;
}

/**
 * Translates any raw text string to the target language if recognized as a UI term.
 */
export const translateText = (rawText, targetLangCode = null) => {
  if (!rawText || typeof rawText !== 'string') return rawText;
  const langCode = targetLangCode || getActiveLanguage().code;
  const clean = rawText.trim();
  const lower = clean.toLowerCase();
  const revMap = getReverseLookupMap();

  let dictKey = revMap.get(lower);
  if (!dictKey) {
    const stripped = lower.replace(/[:.✓→←*•#…]+/g, '').trim();
    dictKey = revMap.get(stripped);
  }

  if (dictKey) {
    if (langCode === 'en' && TRANSLATIONS.en[dictKey]) {
      return TRANSLATIONS.en[dictKey];
    }
    if (TRANSLATIONS[langCode]?.[dictKey]) {
      return TRANSLATIONS[langCode][dictKey];
    }
  }

  return rawText;
};

/**
 * Universal Client-Side DOM Localizer
 * 
 * Automatically translates UI chrome, navigation buttons, taskbar items,
 * status badges, and table headers to the active language across all pages.
 * 
 * STRICT DATA SAFETY GUARANTEE:
 * - NEVER modifies <input> value or <textarea> value (preserves user typed data completely).
 * - NEVER touches elements with contenteditable or data-no-translate="true".
 * - NEVER translates pure numbers, currency figures, emails, phones, GSTIN, PAN, dates, or times.
 * - ONLY translates known UI terms registered in our verified dictionary.
 */
let isApplyingDOM = false;
export const applyDOMTranslations = (targetLangCode = null) => {
  if (typeof document === 'undefined') return;
  if (isApplyingDOM) return;
  isApplyingDOM = true;

  try {
    const langCode = targetLangCode || getActiveLanguage().code;
    const revMap = getReverseLookupMap();
    const targetDict = TRANSLATIONS[langCode] || TRANSLATIONS.en;
    const enDict = TRANSLATIONS.en;

    // 1. Process placeholdered inputs (Translate only the placeholder, NEVER the value attribute)
    const inputs = document.querySelectorAll('input[placeholder], textarea[placeholder]');
    inputs.forEach(input => {
      if (!input._taxproOrigPlaceholder) {
        input._taxproOrigPlaceholder = input.getAttribute('placeholder') || '';
      }
      const orig = input._taxproOrigPlaceholder.trim();
      const lower = orig.toLowerCase().replace(/[:.✓→←*•#…]+/g, '').trim();
      const key = revMap.get(lower);
      if (key && targetDict[key]) {
        input.setAttribute('placeholder', targetDict[key]);
      } else if (langCode === 'en' && key && enDict[key]) {
        input.setAttribute('placeholder', enDict[key]);
      } else if (langCode === 'en' && orig) {
        input.setAttribute('placeholder', orig);
      }
    });

    // 2. Safe recursive walker for UI chrome text nodes across document.body (including menu bar and all pages)
    const root = document.body;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        const val = node.nodeValue?.trim();
        if (!val || val.length < 2 || val.length > 95) return NodeFilter.FILTER_REJECT;

        const parent = node.parentElement;
        if (!parent) return NodeFilter.FILTER_REJECT;

        // STRICT EXCLUSION: Do not touch user data inputs, editable areas, scripts, or styles
        if (
          parent.tagName === 'INPUT' ||
          parent.tagName === 'TEXTAREA' ||
          parent.tagName === 'SELECT' ||
          parent.tagName === 'OPTION' ||
          parent.tagName === 'CODE' ||
          parent.tagName === 'PRE' ||
          parent.tagName === 'SCRIPT' ||
          parent.tagName === 'STYLE' ||
          parent.isContentEditable ||
          parent.closest('[contenteditable="true"]') ||
          parent.closest('[data-no-translate="true"]') ||
          parent.closest('.no-translate') ||
          parent.closest('.taxpro-user-input') ||
          parent.closest('.taxpro-user-data') ||
          parent.closest('.user-data') ||
          parent.closest('.printable-certificate-body')
        ) {
          return NodeFilter.FILTER_REJECT;
        }

        // STRICT EXCLUSION: Do not touch pure numbers, currency figures, emails, phones, dates, PAN/GSTIN
        if (/^[₹$€£¥]?\s*[\d,.-]+%?$/.test(val)) return NodeFilter.FILTER_REJECT;
        if (/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(val)) return NodeFilter.FILTER_REJECT;
        if (/^[A-Z]{5}\d{4}[A-Z]$/.test(val)) return NodeFilter.FILTER_REJECT; // PAN
        if (/^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(val)) return NodeFilter.FILTER_REJECT; // GSTIN
        if (/^(\+91|0)?[6-9]\d{9}$/.test(val)) return NodeFilter.FILTER_REJECT; // Phone
        if (/^\d{1,4}[-/.]\d{1,2}[-/.]\d{1,4}/.test(val)) return NodeFilter.FILTER_REJECT; // Date
        if (/^\d{1,2}:\d{2}(:\d{2})?(\s*(AM|PM|am|pm))?$/.test(val)) return NodeFilter.FILTER_REJECT; // Time

        return NodeFilter.FILTER_ACCEPT;
      }
    });

    const nodesToTranslate = [];
    let currentNode;
    while ((currentNode = walker.nextNode())) {
      nodesToTranslate.push(currentNode);
    }

    for (const node of nodesToTranslate) {
      const currentVal = node.nodeValue.trim();
      const cleanVal = currentVal.toLowerCase().replace(/[:.✓→←*•#…]+/g, '').trim();

      // Lookup in global reverse map (matches terms in any of the 12 languages)
      const key = revMap.get(cleanVal);
      if (!key) continue; // Unregistered text (e.g. user entered names, typed remarks) is completely untouched!

      if (langCode === 'en') {
        const enVal = enDict[key];
        if (enVal && node.nodeValue !== enVal) {
          node.nodeValue = enVal;
        }
      } else if (targetDict[key]) {
        const translated = targetDict[key];
        if (node.nodeValue !== translated) {
          node.nodeValue = translated;
        }
      }
    }
  } catch (err) {
    // Fail-safe: silently proceed without breaking React rendering
  } finally {
    isApplyingDOM = false;
  }
};

// Automatic Global DOM Mutation Observer to re-apply translations when screens change
let domObserver = null;
let domDebounceTimer = null;
export function initDOMObserver() {
  if (typeof window === 'undefined' || typeof MutationObserver === 'undefined') return;
  if (domObserver) return;

  domObserver = new MutationObserver(() => {
    if (domDebounceTimer) clearTimeout(domDebounceTimer);
    domDebounceTimer = setTimeout(() => {
      const lang = getActiveLanguage();
      applyDOMTranslations(lang.code);
    }, 60);
  });

  const target = document.body;
  if (target) {
    domObserver.observe(target, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['class', 'style', 'hidden']
    });
  }
}

// Immediate lifecycle activation
if (typeof window !== 'undefined') {
  // Ensure observer is running as soon as possible
  if (document.readyState === 'loading') {
    window.addEventListener('DOMContentLoaded', () => {
      initDOMObserver();
      const current = getActiveLanguage();
      applyDOMTranslations(current.code);
    });
  } else {
    initDOMObserver();
    const current = getActiveLanguage();
    applyDOMTranslations(current.code);
  }

  // Hook navigation & screen change events
  window.addEventListener('taxpro_screen_changed', () => {
    const lang = getActiveLanguage();
    setTimeout(() => applyDOMTranslations(lang.code), 30);
    setTimeout(() => applyDOMTranslations(lang.code), 160);
  });
}

export const setGlobalLanguage = (langCode) => {
  const target = SUPPORTED_LANGUAGES.find(l => l.code === langCode) || SUPPORTED_LANGUAGES[0];
  try {
    localStorage.setItem('taxpro_language', target.code);
  } catch (e) {}

  // Trigger smooth transition class
  if (typeof document !== 'undefined') {
    document.documentElement.classList.add('taxpro-lang-switching');
    document.documentElement.dir = target.dir || 'ltr';
    document.documentElement.lang = target.code;
    setTimeout(() => {
      document.documentElement.classList.remove('taxpro-lang-switching');
    }, 450);

    // Apply translations across all active DOM pages immediately
    applyDOMTranslations(target.code);
  }

  // Dispatch global event for all active views
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('taxpro_language_changed', { detail: target }));
  }

  return target;
};

export const t = (key, fallback = '') => {
  if (!key) return '';
  const lang = getActiveLanguage();
  const dict = TRANSLATIONS[lang.code] || TRANSLATIONS['en'];
  
  if (dict && dict[key]) return dict[key];

  // Normalized camelCase lookup: "Task History" -> "taskHistory", "AI Studio" -> "aiStudio"
  const normalized = key.toLowerCase()
    .replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
  
  if (dict && dict[normalized]) return dict[normalized];
  
  const lower = key.toLowerCase().replace(/[\s&]+/g, '_');
  if (dict && dict[lower]) return dict[lower];

  return fallback || (TRANSLATIONS['en'] && (TRANSLATIONS['en'][key] || TRANSLATIONS['en'][normalized])) || key;
};

export const useLanguage = () => {
  const [lang, setLang] = useState(getActiveLanguage);

  useEffect(() => {
    const handleUpdate = (e) => {
      const nextLang = e.detail || getActiveLanguage();
      setLang(nextLang);
      applyDOMTranslations(nextLang.code);
    };
    window.addEventListener('taxpro_language_changed', handleUpdate);
    return () => window.removeEventListener('taxpro_language_changed', handleUpdate);
  }, []);

  return {
    currentLanguage: lang,
    setLanguage: setGlobalLanguage,
    t: (key, fallback = '') => {
      if (!key) return '';
      const dict = TRANSLATIONS[lang.code] || TRANSLATIONS['en'];
      if (dict && dict[key]) return dict[key];
      const normalized = key.toLowerCase()
        .replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase())
        .replace(/[^a-zA-Z0-9]/g, '');
      if (dict && dict[normalized]) return dict[normalized];
      const lower = key.toLowerCase().replace(/[\s&]+/g, '_');
      if (dict && dict[lower]) return dict[lower];
      return fallback || (TRANSLATIONS['en'] && (TRANSLATIONS['en'][key] || TRANSLATIONS['en'][normalized])) || key;
    }
  };
};

export default {
  SUPPORTED_LANGUAGES,
  getActiveLanguage,
  setGlobalLanguage,
  translateText,
  applyDOMTranslations,
  initDOMObserver,
  getReverseLookupMap,
  t,
  useLanguage
};
